In [1]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup 
import bosscraper2015
%load_ext autoreload
%autoreload 2

In [105]:
URL = """https://results.baa.org/2023/?event_main_group=runner&
num_results=1000&pid=list&pidp=start&search%5Bsex%5D=Women
&search%5Bage_class%5D=%25&event=R&favorite_remove=9TGHS6FF181D5A"""

URL = """
https://results.baa.org/2023/?page=1&event=R&event_main_group=runner&num_results=25
&pid=list&pidp=start&search%5Bsex%5D=W#
"""

#URL = """
#https://results.baa.org/2023/?page=1&event=R&event_main_group=runner
#&num_results=1000&pid=list&pidp=start&search%5Bsex%5D=M&search%5Bage_class%5D=%25

#"""

r = requests.get(URL) 
  
soup = BeautifulSoup(r.content, 'html.parser') # If this line causes an error, run 'pip install html5lib' or install html5lib 
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <title>
   Boston Athletic Association
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="black" name="apple-mobile-web-app-status-bar-style"/>
  <link href="//results-static.mikatiming.com/2023/boston/../../stages/blue/images/apple-touch-icon.png" rel="apple-touch-icon"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href="//results-static.mikatiming.com/stages/blue/lib/static/bootstrap-3.3.7/css/bootstrap.css" rel="stylesheet"/>
  <link href="//results-static.mikatiming.com/stages/blue/lib/static/styles.build/responsive_2016/style.css" rel="stylesheet"/>
  <link href="/2023/?content=css_event&amp;theme=responsive&amp;event=2023_boston&amp;style=responsive_2016" rel="stylesheet" type="text/css"/>
  <link href="//results-static.mikatiming.com/stages/blue/images/favicon.ico" rel="shortcut icon"/>
  <script src="//assets.mikatiming.com/lib/jquery/1.11.3/jquery.min.js" type="text/javascript">
  </script>
  <script src="//results-static.mikatiming.com/stages/blue/lib/static/bootstrap-3.3.7/js/bootstrap.min.js">
  </script>
  <script src="/2023/?content=ajax2&amp;client=js" type="text/javascript">
  </script>
  <script type="text/javascript">
   var require = {"baseUrl":"\/\/results-static.mikatiming.com\/stages\/blue\/lib\/static","deps":["\/\/results-static.mikatiming.com\/stages\/blue\/lib\/static\/webcomponentsjs-0.7.0\/webcomponents-lite.js"],"paths":{"d3":"d3-3.4.13\/d3","c3":"c3-0.4.8\/c3","moment":"moment.js-2.9.0\/moment-with-locales.min","GDouglasPeuker":"GDouglasPeuker","Mika":"Mika.build","async":"require.js-plugins-1.0.3\/async","combokeys":"combokeys-2.3.0\/dist\/combokeys","videojs":"..\/..\/node_modules\/video.js\/dist\/video.min","hls2":"videojs5-hlsjs-source-handler\/dist\/videojs5-hlsjs-source-handler","nouislider":"noUiSlider-9.2.0\/nouislider.min","screenfull":"screenfull.js-4.0.0\/screenfull","lodashIsEqual":"lodash\/isEqual","Mika\/Cookie":"Mika.build\/Cookie.js?655721dfeb","Mika\/Dialog":"Mika.build\/Dialog.js?1417dbc60b","Mika\/Environment":"Mika.build\/Environment.js?480c237971","Mika\/FavoriteColorMapper":"Mika.build\/FavoriteColorMapper.js?ef8319f63f","Mika\/ImageErrorHandler":"Mika.build\/ImageErrorHandler.js?8d08cffc39","Mika\/ImageViewer":"Mika.build\/ImageViewer.js?109342794a","Mika\/Logger":"Mika.build\/Logger.js?22dc55a65e","Mika\/Map\/FavoriteBar":"Mika.build\/Map\/FavoriteBar.js?ad41f837c2","Mika\/Map\/LatLng":"Mika.build\/Map\/LatLng.js?c3f00d44da","Mika\/Map\/LatLngBounds":"Mika.build\/Map\/LatLngBounds.js?286b63dc46","Mika\/Map\/Map":"Mika.build\/Map\/Map.js?4a81e9b629","Mika\/Map\/Marker\/Cluster\/Cluster":"Mika.build\/Map\/Marker\/Cluster\/Cluster.js?98d485b36d","Mika\/Map\/Marker\/Cluster\/Icon":"Mika.build\/Map\/Marker\/Cluster\/Icon.js?4a282ee401","Mika\/Map\/Marker\/Cluster\/MarkerCluster":"Mika.build\/Map\/Marker\/Cluster\/MarkerCluster.js?2206d06221","Mika\/Map\/Marker\/CollisionSupressor":"Mika.build\/Map\/Marker\/CollisionSupressor.js?060b5889f6","Mika\/Map\/Marker\/CustomImage":"Mika.build\/Map\/Marker\/CustomImage.js?d947dc5ace","Mika\/Map\/Marker\/Flag":"Mika.build\/Map\/Marker\/Flag.js?c5675a7bbb","Mika\/Map\/Marker\/Icons":"Mika.build\/Map\/Marker\/Icons.js?921b6d4038","Mika\/Map\/Marker\/Km":"Mika.build\/Map\/Marker\/Km.js?0009f2eb27","Mika\/Map\/Marker\/Overlay":"Mika.build\/Map\/Marker\/Overlay.js?6f2ae1d409","Mika\/Map\/Marker\/OverlayImage":"Mika.build\/Map\/Marker\/OverlayImage.js?6ddb8c8441","Mika\/Map\/Marker\/Person":"Mika.build\/Map\/Marker\/Person.js?7aa323b218","Mika\/Map\/Object\/Circle":"Mika.build\/Map\/Object\/Circle.js?9f457edf58","Mika\/Map\/Polyline":"Mika.build\/Map\/Polyline.js?7db91e41da","Mika\/Mika":"Mika.build\/Mika.js?1d230059fc","Mika\/PolylineEditor":"Mika.build\/PolylineEditor.js?17ba7e3be6","Mika\/Popover":"Mika.build\/Popover.js?5a1feefec2","Mika\/Quicksearch":"Mika.build\/Quicksearch.js?43699bb952","Mika\/Results\/Board":"Mika.build\/Results\/Board.js?3ce6061f40","Mika\/Results\/Plugins\/favorite_display":"Mika.build\/Results\/Plugins\/favorite_display.js?472451b029","Mika\/Results\/Plugins\/favorites":"Mika.build\/Results\/Plugins\/favorites.js?116759baca","Mika\/Results\/Plugins\/global_option_bar":"Mika.build\/Results\/Plugins\/global_option_bar.js?37bd9023e1","Mika\/Results\/Plugins\/graph":"Mika.build\/Results\/Plugins\/graph.js?8adb962b04","Mika\/Results\/Plugins\/list":"Mika.build\/Results\/Plugins\/list.js?d0ac21ca40","Mika\/Results\/Plugins\/list_responsive":"Mika.build\/Results\/Plugins\/list_responsive.js?7599dfc7aa","Mika\/Results\/Plugins\/main_buttons":"Mika.build\/Results\/Plugins\/main_buttons.js?a4870cae79","Mika\/Results\/Plugins\/map":"Mika.build\/Results\/Plugins\/map.js?6c639c117d","Mika\/Results\/Plugins\/overlays":"Mika.build\/Results\/Plugins\/overlays.js?08c8f98e5a","Mika\/Results\/Plugins\/pacegraph":"Mika.build\/Results\/Plugins\/pacegraph.js?ca3af2b47f","Mika\/Results\/Plugins\/race_flow_table":"Mika.build\/Results\/Plugins\/race_flow_table.js?9edac01872","Mika\/Results\/Plugins\/remote_content":"Mika.build\/Results\/Plugins\/remote_content.js?d2147f7d1d","Mika\/Results\/Plugins\/strings":"Mika.build\/Results\/Plugins\/strings.js?e1c3fdfe09","Mika\/Results\/Requester":"Mika.build\/Results\/Requester.js?1125084685","Mika\/SearchProvider":"Mika.build\/SearchProvider.js?f2f0ec44c4","Mika\/Sharer\/Networks\/base":"Mika.build\/Sharer\/Networks\/base.js?fb6ba1eb65","Mika\/Sharer\/Networks\/facebook":"Mika.build\/Sharer\/Networks\/facebook.js?87398d5603","Mika\/Sharer\/Networks\/googleplus":"Mika.build\/Sharer\/Networks\/googleplus.js?608816c3ad","Mika\/Sharer\/Networks\/twitter":"Mika.build\/Sharer\/Networks\/twitter.js?a16d7ce4b9","Mika\/Sharer\/Networks\/whatsapp":"Mika.build\/Sharer\/Networks\/whatsapp.js?a56ff996ca","Mika\/Sharer\/Networks\/xing":"Mika.build\/Sharer\/Networks\/xing.js?1bd22b6d66","Mika\/Sharer\/Sharer":"Mika.build\/Sharer\/Sharer.js?fc3b225b1a","Mika\/Ticker":"Mika.build\/Ticker.js?12f899ca52","Mika\/Timer":"Mika.build\/Timer.js?d19e2b8a37","Mika\/Tools":"Mika.build\/Tools.js?adab49a49a","Mika\/Tracker":"Mika.build\/Tracker.js?2a314f808e","Mika\/Uploader":"Mika.build\/Uploader.js?e0c3b13e8a","Mika\/VideoViewer":"Mika.build\/VideoViewer.js?4c0122b067"},"config":{"Mika\/Mika":{"debug":false,"display_errors":true,"pathIcons":"\/\/assets.mikatiming.com\/img\/mt\/results\/default","language":"EN_CAP","global_event_id":"2023_boston","static_uri":"\/\/results-static.mikatiming.com\/stages\/blue"},"Mika\/Logger":{"debug":false},"Mika\/Quicksearch":{"pid":null,"not_found_string":"Sorry, no results found!"},"Mika\/ImageViewer":{"pathIcons":"\/\/assets.mikatiming.com\/img\/mt\/results\/default","sharerActive":false},"Mika\/VideoViewer":{"pathIcons":"\/\/assets.mikatiming.com\/img\/mt\/results\/default","modalWidth":null},"Mika\/Map\/Map":{"mapProvider":"here"},"Mika\/Sharer\/Sharer":{"pathSharerIcons":"\/\/assets.mikatiming.com\/img\/mt\/sharer\/","buttonSize":"xs"},"Mika\/Map\/Marker\/Person":[]}}
  </script>
  <script src="//results-static.mikatiming.com/stages/blue/lib/static/require.js-2.3.6/require.min.js" type="text/javascript">
  </script>
  <script src="//results-static.mikatiming.com/stages/blue/lib/static/Emitter.js" type="text/javascript">
  </script>
  <meta content="yes" name="apple-mobile-web-app-capable">
   <script type="text/javascript">
    // create helper function to handle the image loading errors
        var mikaImageErrorHandler = function (image) {
            require(["Mika/ImageErrorHandler"], function (ImageErrorHandler) {
                var que = ImageErrorHandler.queueImageGeneration(image.dataset.generateSrcUrl, image.dataset.imageHash, image.src);
                setTimeout(function () {
                     ImageErrorHandler.statusMissingImages(que);
                }, 1100);
            })
        };
        require(["Mika/Mika", "require"], function (Mika, require) {
            new Mika();
            require(["Mika/Dialog", "Mika/Popover", "Mika/ImageViewer", "Mika/Timer"]);
        });
   </script>
  </meta>
 </head>
 <body class="pid-list content-list view-public branch-production site-2023_boston event-R">
  <header class="hidden-xs">
   <div class="container">
    <div class="logo row">
     <a href="/2023/?pidp=start">
      <img alt="" class="logo-screen" src="//results-static.mikatiming.com/2023/boston/../boston/styles/responsive_2016/baa_logo.svg"/>
     </a>
    </div>
   </div>
  </header>
  <nav class="navbar navbar-default navbar-top navbar-fixed-top">
   <div class="container">
    <div class="navbar-header">
     <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
      <span class="sr-only">
       Toggle navigation
      </span>
      <span class="icon-bar">
      </span>
      <span class="icon-bar">
      </span>
      <span class="icon-bar">
      </span>
     </button>
     <a class="navbar-brand" href="/2023/?pidp=start">
      <img alt="" class="hidden-sm hidden-md hidden-lg" src="//results-static.mikatiming.com/2023/boston/../boston/styles/responsive_2016/baa_logo.svg"/>
      <span class="hidden-xs">
       Boston Athletic Association | 2023
      </span>
     </a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
     <ul class="nav navbar-nav hidden-sm hidden-md hidden-lg">
      <li class="active">
       <a class="nav-pid-start tt-help" href="/2023/?event=R&amp;event_main_group=runner&amp;pid=start&amp;pidp=start&amp;search%5Bsex%5D=W" title="Search for individual participants or select result lists">
        <span>
         Results
        </span>
       </a>
      </li>
      <li>
       <a class="nav-pid-leaderboard tt-help" href="/2023/?pid=leaderboard&amp;pidp=start" title="Follow the leading group throughout the race">
        <span>
         Leaderboard
        </span>
       </a>
      </li>
      <li>
       <a class="nav-pid-tracking tt-help" href="/2023/?pid=tracking&amp;pidp=start" title="Tracking allows you to follow your selected runners on a course map">
        <span>
         Tracking
        </span>
       </a>
      </li>
      <li>
       <a class="nav-pid-favorites tt-help" href="/2023/?pid=favorites&amp;pidp=start" title="Follow your runners in a list view">
        <span>
         My Runners
        </span>
       </a>
      </li>
     </ul>
     <ul class="nav navbar-nav navbar-right">
      <li class="">
       <a class="" href="https://www.baa.org" role="button">
        Back to baa.org
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <!-- header end -->
  <!-- main start -->
  <script async="" src="https://www.googletagmanager.com/gtag/js">
  </script>
  <script>
   var mt_tracker = {};

         window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            require(['Mika/Tracker'], function(tracker) {
                tracker.setGtagConfig(["G-X7BG41Z7K0","G-0YSHTKMVGL"], {"page_title":"list","send_page_view":false,"meeting_id":"9TGHS6FF1F5","meeting_name":"Boston Athletic Association | 2023","meeting_year":"2023","results_view":"public"});
                tracker.track('page_view');
                mt_tracker = tracker;
            });
  </script>
  <section class="section-nav container">
   <nav class="navbar navbar-default row navbar-main hidden-xs">
    <div class="container">
     <ul class="nav navbar-nav">
      <li class="active nav-pid-start">
       <a class="tt-help" href="/2023/?pid=start&amp;pidp=start" title="Search for individual participants or select result lists">
        <span>
         Results
        </span>
       </a>
      </li>
      <li class="nav-pid-leaderboard">
       <a class="tt-help" href="/2023/?pid=leaderboard&amp;pidp=leaderboard" title="Follow the leading group throughout the race">
        <span>
         Leaderboard
        </span>
       </a>
      </li>
      <li class="nav-pid-tracking">
       <a class="tt-help" href="/2023/?pid=tracking&amp;pidp=tracking" title="Tracking allows you to follow your selected runners on a course map">
        <span>
         Tracking
        </span>
       </a>
      </li>
      <li class="nav-pid-favorites">
       <a class="tt-help" href="/2023/?pid=favorites&amp;pidp=favorites" title="Follow your runners in a list view">
        <span>
         My Runners
        </span>
       </a>
      </li>
      <li class="dropdown hide">
       <a aria-expanded="true" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0);" id="navbar-main-dropdown">
        More
        <span class="caret">
        </span>
       </a>
       <ul aria-labelledby="navbar-main-dropdown" class="dropdown-menu">
       </ul>
      </li>
      <script type="text/javascript">
       jQuery("#navbar-main-dropdown").dropdown();
                var menuResizeHandler = function () {
                    var container   = jQuery(".navbar-main .container");
                    var navbar   = jQuery(".navbar-main .nav");
                    var currentWidth = 0;
                    var dropdown = navbar.find("li.dropdown");
                    // quickly show it and get the width
                    dropdown.removeClass("hide");
                    var dropdownWidth = dropdown.width();
                    var quicksearchWidth = jQuery(".navbar-main .quicksearch-form").width();
                    currentWidth += quicksearchWidth;
                    var menuEntries = navbar.find("li:not(.dropdown)");
                    menuEntries.each(function (i) {
                        navbar.append(this);
                    });
                    navbar.append(dropdown);
                    dropdown.addClass("hide").removeClass("active");

                    var maxWidth = container.width();
                    menuEntries.each(function (i) {
                        currentWidth += jQuery(this).width();

                        var next = false;
                        if (typeof menuEntries[i+1] !== "undefined") {
                            next = menuEntries[i+1];
                        }
                        var currentIsAboveMaxWidth = (currentWidth > maxWidth);
                        var currentIsNotLastAndPlusDropdownIsAboveMaxWidth = ((currentWidth + dropdownWidth > maxWidth) && i != menuEntries.length-1);
                        var currentPlusNextIsAboveMaxWidth = (next && currentWidth + jQuery(next).width() > maxWidth);
                        //console.log("%s: width: %s, is above: %s, notlast: %s, plusnext: %s", jQuery(this).text(), currentWidth, currentIsAboveMaxWidth, currentIsNotLastAndPlusDropdownIsAboveMaxWidth, currentPlusNextIsAboveMaxWidth)
                        if(currentIsAboveMaxWidth || currentIsNotLastAndPlusDropdownIsAboveMaxWidth || currentPlusNextIsAboveMaxWidth) {
                            jQuery(this).find("a").popover("destroy");
                            dropdown.find("ul").append(this);
                            dropdown.removeClass("hide");
                            if (jQuery(this).hasClass("active")) {
                                dropdown.addClass("active");
                            }
                        }
                    });

                };
                jQuery(document).on("ready", menuResizeHandler);
                var lastWidth = 0;
                jQuery(window).on("resize", function () {
                    lastWidth = window.innerWidth;
                    setTimeout(function () {
                        if (lastWidth == window.innerWidth) {
                            menuResizeHandler();
                        }
                    }, 100);
                });
      </script>
     </ul>
    </div>
   </nav>
   <!-- menu end -->
  </section>
  <section class="section-main">
   <div class="container" id="main-content">
    <div class="row">
     <div class="cbox-main pid-list col-xs-12" id="cbox-main">
      <!-- cbox include start -->
      <div class="row">
       <div class="col-xs-10">
        <h2>
         Results: Runner
        </h2>
       </div>
      </div>
      <ul class="row-xs list-group list-info">
       <li class="list-group-item">
        11423 Results | Unofficial Results |
        <span class="sex">
         Women
        </span>
       </li>
      </ul>
      <div class="col-sm-12 row-xs">
       <ul class="list-group list-group-multicolumn">
        <li class="list-group row list-group-item list-group-header">
         <div class="col-xs-12 col-sm-12 col-md-5 list-field-wrap">
          <div class="row">
           <div class="list-field type-place place-secondary hidden-xs" style="width: 50px">
            Place Overall
           </div>
           <div class="list-field type-place place-primary" style="width: 50px">
            Place Gender
           </div>
           <div class="list-field type-place place-secondary hidden-xs" style="width: 50px">
            Place Division
           </div>
           <div class="list-field type-fullname">
            Name
           </div>
          </div>
         </div>
         <div class="col-xs-12 col-sm-12 col-md-7 hidden-xs hidden-sm list-field-wrap">
          <div class="pull-left">
           <div class="row">
            <div class="list-field type-field" style="width: 100px">
             <div class="visible-xs-block visible-sm-block list-label">
              Team
             </div>
             Team
            </div>
            <div class="list-field type-field" style="width: 45px">
             <div class="visible-xs-block visible-sm-block list-label">
              BIB
             </div>
             BIB
            </div>
           </div>
          </div>
          <div class="pull-right">
           <div class="row">
            <div class="split list-field type-time">
             <div class="visible-xs-block visible-sm-block list-label">
              HALF
             </div>
             HALF
            </div>
            <div class="split list-field type-time">
             <div class="visible-xs-block visible-sm-block list-label">
              Finish Net
             </div>
             Finish Net
            </div>
            <div class="split list-field type-time">
             <div class="visible-xs-block visible-sm-block list-label">
              Finish Gun
             </div>
             Finish Gun
            </div>
            <div class="list-field type-favorite" style="width: 13px">
            </div>
           </div>
          </div>
         </div>
        </li>
        <li class="list-active list-group-item row">
         <div class="col-xs-12 col-sm-12 col-md-5 list-field-wrap">
          <div class="row">
           <div class="list-field type-place place-secondary hidden-xs numeric" style="width: 50px">
            36
           </div>
           <div class="list-field type-place place-primary numeric" style="width: 50px">
            1
           </div>
           <div class="list-field type-place place-secondary hidden-xs numeric" style="width: 50px">
            1
           </div>
           <h4 class="list-field type-fullname">
            <a href="?content=detail&amp;fpid=list&amp;pid=list&amp;idp=9TGHS6FF181F14&amp;lang=EN_CAP&amp;event=R&amp;event_main_group=runner&amp;pidp=start&amp;search%5Bsex%5D=W&amp;search_event=R">
             Obiri, Hellen
            </a>
           </h4>
          </div>
         </div>
         <div class="col-xs-12 col-sm-12 col-md-7 list-field-wrap">
          <div class="pull-left">
           <div class="row">
            <div class="list-field type-field" style="width: 100px">
             <div class="visible-xs-block visible-sm-block list-label">
              Team
             </div>
             <span class="text-muted">
              –
             </span>
            </div>

In [106]:
for row in soup.find_all('a'):
    print(row.get_text())

Boston Athletic Association | 2023

Results
Leaderboard
Tracking
My Runners
Back to baa.org
Results
Leaderboard
Tracking
My Runners

                    More


Obiri, Hellen

Beriso, Amane

Salpeter, Lonah

Yeshaneh, Ababel

Bates, Emma

Weldu, Nazret

Tanui, Angela

Gebremaryam, Hiwot

Ngugi, Mary

Gebreslase, Gotytom

Tuliamuk, Aliphine

Jepkosgei, Joyciline

Cheptoo, Viola

Rojas, Nell

Brinkman, Nienke

Chepchirchir, Celestine

Hall, Sara

Linden, Desiree

Chepkirui, Vibian

Frisbie, Annie

Baysa, Atsede

Rohrer, Anna

Devore, Sydney

Montoya, Maggie

Blaney, Anne-Marie

Back / New Search
Reload
Print
1
2
3
...
457
>

In [107]:
#WOMEN
person_dicts = []
for x in range(1,round(11423/25)) :
    print('dicts length',len(person_dicts))
    
    URL2 = f"""
https://results.baa.org/2023/?page={x}&event=R&event_main_group=runner&num_results=25
&pid=list&pidp=start&search%5Bsex%5D=W#
"""
    r = requests.get(URL2) 
  
    soup = BeautifulSoup(r.content, 'html.parser')
    # for row in soup.find_all('div'):
    #     print(row.get_text())

    table = soup.find_all('div',class_="row")[1:2][0]
    rows = table.find_all('div',class_="row")[1:]
    print(len(rows))

    for row_ind in range(3,len(rows),3):#len(rows),3):
       # try :
        if row_ind + 2 < len(rows) :
            person_dict = {}
            names_row = rows[row_ind].get_text().strip().split('\n')
            person_dict['Place Overall'] = names_row[0]
            person_dict['Place Gender'] = names_row[1]
            person_dict['Place Division'] = names_row[2]
            person_dict['full_name'] = names_row[-1]
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

            person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = rows[row_ind + 1].get_text().strip().split('\n')[1][3:]
            times = rows[row_ind + 2].get_text().strip().split('\n')
            person_dict['half_marathon_split'] = times[0][4:]
            person_dict['full_split'] = times[1][10:]
            person_dict['finish_gun_time'] = times[2][10:]
            #print(row_ind,rows[row_ind].get_text())
            person_dicts.append(person_dict)
#         except :
#             #rint(rows[row_ind])
    
#             #print(rows[row_ind])
#person_dicts
df_boston_2023_women = pd.DataFrame.from_dict(person_dicts)
df_boston_2023_women

dicts length 0
79
dicts length 25
79
dicts length 50
79
dicts length 75
79
dicts length 100
79
dicts length 125
79
dicts length 150
79
dicts length 175
79
dicts length 200
79
dicts length 225
79
dicts length 250
79
dicts length 275
79
dicts length 300
79
dicts length 325
79
dicts length 350
79
dicts length 375
79
dicts length 400
79
dicts length 425
79
dicts length 450
79
dicts length 475
79
dicts length 500
79
dicts length 525
79
dicts length 550
79
dicts length 575
79
dicts length 600
79
dicts length 625
79
dicts length 650
79
dicts length 675
79
dicts length 700
79
dicts length 725
79
dicts length 750
79
dicts length 775
79
dicts length 800
79
dicts length 825
79
dicts length 850
79
dicts length 875
79
dicts length 900
79
dicts length 925
79
dicts length 950
79
dicts length 975
79
dicts length 1000
79
dicts length 1025
79
dicts length 1050
79
dicts length 1075
79
dicts length 1100
79
dicts length 1125
79
dicts length 1150
79
dicts length 1175
79
dicts length 1200
79
dicts length 1225
79
dicts length 1250
79
dicts length 1275
79
dicts length 1300
79
dicts length 1325
79
dicts length 1350
79
dicts length 1375
79
dicts length 1400
79
dicts length 1425
79
dicts length 1450
79
dicts length 1475
79
dicts length 1500
79
dicts length 1525
79
dicts length 1550
79
dicts length 1575
79
dicts length 1600
79
dicts length 1625
79
dicts length 1650
79
dicts length 1675
79
dicts length 1700
79
dicts length 1725
79
dicts length 1750
79
dicts length 1775
79
dicts length 1800
79
dicts length 1825
79
dicts length 1850
79
dicts length 1875
79
dicts length 1900
79
dicts length 1925
79
dicts length 1950
79
dicts length 1975
79
dicts length 2000
79
dicts length 2025
79
dicts length 2050
79
dicts length 2075
79
dicts length 2100
79
dicts length 2125
79
dicts length 2150
79
dicts length 2175
79
dicts length 2200
79
dicts length 2225
79
dicts length 2250
79
dicts length 2275
79
dicts length 2300
79
dicts length 2325
79
dicts length 2350
79
dicts length 2375
79
dicts length 2400
79
dicts length 2425
79
dicts length 2450
79
dicts length 2475
79
dicts length 2500
79
dicts length 2525
79
dicts length 2550
79
dicts length 2575
79
dicts length 2600
79
dicts length 2625
79
dicts length 2650
79
dicts length 2675
79
dicts length 2700
79
dicts length 2725
79
dicts length 2750
79
dicts length 2775
79
dicts length 2800
79
dicts length 2825
79
dicts length 2850
79
dicts length 2875
79
dicts length 2900
79
dicts length 2925
79
dicts length 2950
79
dicts length 2975
79
dicts length 3000
79
dicts length 3025
79
dicts length 3050
79
dicts length 3075
79
dicts length 3100
79
dicts length 3125
79
dicts length 3150
79
dicts length 3175
79
dicts length 3200
79
dicts length 3225
79
dicts length 3250
79
dicts length 3275
79
dicts length 3300
79
dicts length 3325
79
dicts length 3350
79
dicts length 3375
79
dicts length 3400
79
dicts length 3425
79
dicts length 3450
79
dicts length 3475
79
dicts length 3500
79
dicts length 3525
79
dicts length 3550
79
dicts length 3575
79
dicts length 3600
79
dicts length 3625
79
dicts length 3650
79
dicts length 3675
79
dicts length 3700
79
dicts length 3725
79
dicts length 3750
79
dicts length 3775
79
dicts length 3800
79
dicts length 3825
79
dicts length 3850
79
dicts length 3875
79
dicts length 3900
79
dicts length 3925
79
dicts length 3950
79
dicts length 3975
79
dicts length 4000
79
dicts length 4025
79
dicts length 4050
79
dicts length 4075
79
dicts length 4100
79
dicts length 4125
79
dicts length 4150
79
dicts length 4175
79
dicts length 4200
79
dicts length 4225
79
dicts length 4250
79
dicts length 4275
79
dicts length 4300
79
dicts length 4325
79
dicts length 4350
79
dicts length 4375
79
dicts length 4400
79
dicts length 4425
79
dicts length 4450
79
dicts length 4475
79
dicts length 4500
79
dicts length 4525
79
dicts length 4550
79
dicts length 4575
79
dicts length 4600
79
dicts length 4625
79
dicts length 4650
79
dicts length 4675
79
dicts length 4700
79
dicts length 4725
79
dicts length 4750
79
dicts length 4775
79
dicts length 4800
79
dicts length 4825
79
dicts length 4850
79
dicts length 4875
79
dicts length 4900
79
dicts length 4925
79
dicts length 4950
79
dicts length 4975
79
dicts length 5000
79
dicts length 5025
79
dicts length 5050
79
dicts length 5075
79
dicts length 5100
79
dicts length 5125
79
dicts length 5150
79
dicts length 5175
79
dicts length 5200
79
dicts length 5225
79
dicts length 5250
79
dicts length 5275
79
dicts length 5300
79
dicts length 5325
79
dicts length 5350
79
dicts length 5375
79
dicts length 5400
79
dicts length 5425
79
dicts length 5450
79
dicts length 5475
79
dicts length 5500
79
dicts length 5525
79
dicts length 5550
79
dicts length 5575
79
dicts length 5600
79
dicts length 5625
79
dicts length 5650
79
dicts length 5675
79
dicts length 5700
79
dicts length 5725
79
dicts length 5750
79
dicts length 5775
79
dicts length 5800
79
dicts length 5825
79
dicts length 5850
79
dicts length 5875
79
dicts length 5900
79
dicts length 5925
79
dicts length 5950
79
dicts length 5975
79
dicts length 6000
79
dicts length 6025
79
dicts length 6050
79
dicts length 6075
79
dicts length 6100
79
dicts length 6125
79
dicts length 6150
79
dicts length 6175
79
dicts length 6200
79
dicts length 6225
79
dicts length 6250
79
dicts length 6275
79
dicts length 6300
79
dicts length 6325
79
dicts length 6350
79
dicts length 6375
79
dicts length 6400
79
dicts length 6425
79
dicts length 6450
79
dicts length 6475
79
dicts length 6500
79
dicts length 6525
79
dicts length 6550
79
dicts length 6575
79
dicts length 6600
79
dicts length 6625
79
dicts length 6650
79
dicts length 6675
79
dicts length 6700
79
dicts length 6725
79
dicts length 6750
79
dicts length 6775
79
dicts length 6800
79
dicts length 6825
79
dicts length 6850
79
dicts length 6875
79
dicts length 6900
79
dicts length 6925
79
dicts length 6950
79
dicts length 6975
79
dicts length 7000
79
dicts length 7025
79
dicts length 7050
79
dicts length 7075
79
dicts length 7100
79
dicts length 7125
79
dicts length 7150
79
dicts length 7175
79
dicts length 7200
79
dicts length 7225
79
dicts length 7250
79
dicts length 7275
79
dicts length 7300
79
dicts length 7325
79
dicts length 7350
79
dicts length 7375
79
dicts length 7400
79
dicts length 7425
79
dicts length 7450
79
dicts length 7475
79
dicts length 7500
79
dicts length 7525
79
dicts length 7550
79
dicts length 7575
79
dicts length 7600
79
dicts length 7625
79
dicts length 7650
79
dicts length 7675
79
dicts length 7700
79
dicts length 7725
79
dicts length 7750
79
dicts length 7775
79
dicts length 7800
79
dicts length 7825
79
dicts length 7850
79
dicts length 7875
79
dicts length 7900
79
dicts length 7925
79
dicts length 7950
79
dicts length 7975
79
dicts length 8000
79
dicts length 8025
79
dicts length 8050
79
dicts length 8075
79
dicts length 8100
79
dicts length 8125
79
dicts length 8150
79
dicts length 8175
79
dicts length 8200
79
dicts length 8225
79
dicts length 8250
79
dicts length 8275
79
dicts length 8300
79
dicts length 8325
79
dicts length 8350
79
dicts length 8375
79
dicts length 8400
79
dicts length 8425
79
dicts length 8450
79
dicts length 8475
79
dicts length 8500
79
dicts length 8525
79
dicts length 8550
79
dicts length 8575
79
dicts length 8600
79
dicts length 8625
79
dicts length 8650
79
dicts length 8675
79
dicts length 8700
79
dicts length 8725
79
dicts length 8750
79
dicts length 8775
79
dicts length 8800
79
dicts length 8825
79
dicts length 8850
79
dicts length 8875
79
dicts length 8900
79
dicts length 8925
79
dicts length 8950
79
dicts length 8975
79
dicts length 9000
79
dicts length 9025
79
dicts length 9050
79
dicts length 9075
79
dicts length 9100
79
dicts length 9125
79
dicts length 9150
79
dicts length 9175
79
dicts length 9200
79
dicts length 9225
79
dicts length 9250
79
dicts length 9275
79
dicts length 9300
79
dicts length 9325
79
dicts length 9350
79
dicts length 9375
79
dicts length 9400
79
dicts length 9425
79
dicts length 9450
79
dicts length 9475
79
dicts length 9500
79
dicts length 9525
79
dicts length 9550
79
dicts length 9575
79
dicts length 9600
79
dicts length 9625
79
dicts length 9650
79
dicts length 9675
79
dicts length 9700
79
dicts length 9725
79
dicts length 9750
79
dicts length 9775
79
dicts length 9800

79
dicts length 9825
79
dicts length 9850
79
dicts length 9875
79
dicts length 9900
79
dicts length 9925
79
dicts length 9950
79
dicts length 9975
79
dicts length 10000
79
dicts length 10025
79
dicts length 10050
79
dicts length 10075
79
dicts length 10100
79
dicts length 10125
79
dicts length 10150
79
dicts length 10175
79
dicts length 10200
79
dicts length 10225
79
dicts length 10250
79
dicts length 10275
79
dicts length 10300
79
dicts length 10325
79
dicts length 10350
79
dicts length 10375
79
dicts length 10400
79
dicts length 10425
79
dicts length 10450
79
dicts length 10475
79
dicts length 10500
79
dicts length 10525
79
dicts length 10550
79
dicts length 10575
79
dicts length 10600
79
dicts length 10625
79
dicts length 10650
79
dicts length 10675
79
dicts length 10700
79
dicts length 10725
79
dicts length 10750
79
dicts length 10775
79
dicts length 10800
79
dicts length 10825
79
dicts length 10850
79
dicts length 10875
79
dicts length 10900
79
dicts length 10925
79
dicts length 10950
79
dicts length 10975
79
dicts length 11000
79
dicts length 11025
79
dicts length 11050
79
dicts length 11075
79
dicts length 11100
79
dicts length 11125
79
dicts length 11150
79
dicts length 11175
79
dicts length 11200
79
dicts length 11225
79
dicts length 11250
79
dicts length 11275
79
dicts length 11300
79
dicts length 11325
79
dicts length 11350
79
dicts length 11375
79

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,36,1,1,"Obiri, Hellen",Hellen,Obiri,–,122,01:11:29,02:21:38,02:21:38
1,40,2,2,"Beriso, Amane",Amane,Beriso,–,102,01:11:30,02:21:50,02:21:50
2,41,3,3,"Salpeter, Lonah",Lonah,Salpeter,–,105,01:11:29,02:21:57,02:21:57
3,42,4,4,"Yeshaneh, Ababel",Ababel,Yeshaneh,–,116,01:11:30,02:22:00,02:22:00
4,44,5,5,"Bates, Emma",Emma,Bates,–,121,01:11:30,02:22:10,02:22:10
...,...,...,...,...,...,...,...,...,...,...,...
11395,26566,11396,4873,"Kossmann, Emily",Emily,Kossmann,–,24649,02:41:39,06:03:49,06:03:57
11396,26567,11397,811,"Detora, Joanne",Joanne,Detora,–,31444,02:52:20,06:03:56,06:10:11
11397,26569,11398,1878,"Bishop, Samantha",Samantha,Bishop,–,31117,02:56:33,06:04:17,06:08:56
11398,26570,11399,525,"Tomlinson, Jan",Jan,Tomlinson,–,30912,02:56:47,06:04:25,06:08:09
11399,26573,11400,1817,"Mooney, Janet",Janet,Mooney,–,17738,02:47:36,06:04:46,06:05:07

In [112]:
person_dicts = []
for x in range(round(11425/25),round(11450/25)) :
    print('dicts length',len(person_dicts))
    
    URL3 = f"""
https://results.baa.org/2023/?page={x}&event=R&event_main_group=runner&num_results=25
&pid=list&pidp=start&search%5Bsex%5D=W#
"""
    r = requests.get(URL3) 
  
    soup = BeautifulSoup(r.content, 'html.parser')
    # for row in soup.find_all('div'):
    #     print(row.get_text())

    table = soup.find_all('div',class_="row")[1:2][0]
    rows = table.find_all('div',class_="row")[1:]
    print(len(rows))

    for row_ind in range(3,len(rows),3):#len(rows),3):
       # try :
        if row_ind + 2 < len(rows) :
            person_dict = {}
            names_row = rows[row_ind].get_text().strip().split('\n')
            person_dict['Place Overall'] = names_row[0]
            person_dict['Place Gender'] = names_row[1]
            person_dict['Place Division'] = names_row[2]
            person_dict['full_name'] = names_row[-1]
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

            person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = rows[row_ind + 1].get_text().strip().split('\n')[1][3:]
            times = rows[row_ind + 2].get_text().strip().split('\n')
            person_dict['half_marathon_split'] = times[0][4:]
            person_dict['full_split'] = times[1][10:]
            person_dict['finish_gun_time'] = times[2][10:]
            #print(row_ind,rows[row_ind].get_text())
            person_dicts.append(person_dict)
#         except :
#             #rint(rows[row_ind])
    
#             #print(rows[row_ind])
#person_dicts
df_boston_2023_women_2 = pd.DataFrame.from_dict(person_dicts)
df_boston_2023_women_2

dicts length 0
73

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,26576,11401,4874,"Sullivan, Megan",Megan,Sullivan,–,26897,02:48:02,06:05:10,06:06:51
1,26577,11402,4875,"O'Brien, Ava",Ava,O'Brien,–,29960,02:49:21,06:05:11,06:10:58
2,26579,11403,812,"Serrano, Milagros",Milagros,Serrano,–,26260,02:45:38,06:05:16,06:09:33
3,26580,11404,526,"Walker, Yvonne",Yvonne,Walker,–,24038,02:47:07,06:05:35,06:06:00
4,26582,11405,813,"Curl, Sharon",Sharon,Curl,–,31079,02:48:17,06:05:36,06:10:05
5,26583,11406,4876,"O'Loughlin, Elaine",Elaine,O'Loughlin,–,29185,02:46:06,06:05:38,06:09:03
6,26584,11407,4877,"Bierman, Molly",Molly,Bierman,–,26147,02:36:46,06:05:49,06:07:01
7,26585,11408,4878,"Hall, Hilary",Hilary,Hall,–,24679,02:47:39,06:05:57,06:06:10
8,26587,11409,4879,"Hancock, Kendra",Kendra,Hancock,–,25668,02:52:40,06:06:47,06:10:46
9,26588,11410,1204,"Lesmana, Sulistyani",Sulistyani,Lesmana,–,29076,02:57:31,06:07:33,06:10:06
10,26590,11411,61,"Broussard, Anne",Anne,Broussard,New England 65+ Runners Club,29344,03:02:39,06:08:21,06:10:55
11,26591,11412,4880,"Borne, Katharine",Katharine,Borne,–,24829,02:45:27,06:08:22,06:08:48
12,26595,11413,1205,"Hofeldt, Kimberly",Kimberly,Hofeldt,–,24881,02:42:17,06:09:05,06:10:07
13,26598,11414,1206,"Morrison, Kimberly",Kimberly,Morrison,–,24594,02:45:56,06:09:47,06:10:03
14,26599,11415,1207,"Tighe, Jamie",Jamie,Tighe,–,24621,02:43:21,06:10:25,06:10:40
15,26600,11416,814,"Parker, Joni",Joni,Parker,–,23807,02:35:09,06:11:02,06:17:24
16,26603,11417,62,"Xenos, Sandra",Sandra,Xenos,–,15957,02:54:12,06:16:46,06:21:47
17,26607,11418,4881,"Williams, Alexandria",Alexandria,Williams,–,6999,02:55:30,06:18:59,06:22:21
18,26610,11419,527,"Magdaleno, Roselia",Roselia,Magdaleno,–,30985,02:52:35,06:25:34,06:29:38
19,26611,11420,4882,"Cooper, Rosalyn",Rosalyn,Cooper,–,14770,02:17:46,06:26:09,06:32:38
20,26613,11421,4883,"Myers, Laryssa",Laryssa,Myers,–,7781,02:42:01,06:30:07,06:35:37
21,26621,11422,815,"Foulds, Rhonda",Rhonda,Foulds,–,7552,03:09:48,06:56:34,07:02:44
22,26624,11423,4884,"Singh, Angela",Angela,Singh,–,25655,03:17:39,07:20:31,07:21:24

In [113]:
df_women_2023_all = pd.concat([df_boston_2023_women,df_boston_2023_women_2])
df_women_2023_all

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,36,1,1,"Obiri, Hellen",Hellen,Obiri,–,122,01:11:29,02:21:38,02:21:38
1,40,2,2,"Beriso, Amane",Amane,Beriso,–,102,01:11:30,02:21:50,02:21:50
2,41,3,3,"Salpeter, Lonah",Lonah,Salpeter,–,105,01:11:29,02:21:57,02:21:57
3,42,4,4,"Yeshaneh, Ababel",Ababel,Yeshaneh,–,116,01:11:30,02:22:00,02:22:00
4,44,5,5,"Bates, Emma",Emma,Bates,–,121,01:11:30,02:22:10,02:22:10
...,...,...,...,...,...,...,...,...,...,...,...
18,26610,11419,527,"Magdaleno, Roselia",Roselia,Magdaleno,–,30985,02:52:35,06:25:34,06:29:38
19,26611,11420,4882,"Cooper, Rosalyn",Rosalyn,Cooper,–,14770,02:17:46,06:26:09,06:32:38
20,26613,11421,4883,"Myers, Laryssa",Laryssa,Myers,–,7781,02:42:01,06:30:07,06:35:37
21,26621,11422,815,"Foulds, Rhonda",Rhonda,Foulds,–,7552,03:09:48,06:56:34,07:02:44
22,26624,11423,4884,"Singh, Angela",Angela,Singh,–,25655,03:17:39,07:20:31,07:21:24

In [114]:
df_women_2023_all.to_csv('boston_marathon_results_2023_women.csv')

In [46]:
df_boston_2023 = pd.DataFrame.from_dict(person_dicts)
df_boston_2023

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,1,1,1,"Chebet, Evans",Evans,Chebet,–,1,01:02:20,02:05:54,02:05:54
1,2,2,2,"Geay, Gabriel",Gabriel,Geay,–,3,01:02:20,02:06:04,02:06:04
2,3,3,3,"Kipruto, Benson",Benson,Kipruto,–,5,01:02:19,02:06:06,02:06:06
3,4,4,4,"Korir, Albert",Albert,Korir,–,19,01:02:20,02:08:01,02:08:01
4,5,5,5,"Talbi, Zouhair",Zouhair,Talbi,–,31,01:02:20,02:08:35,02:08:35
...,...,...,...,...,...,...,...,...,...,...,...
995,1047,996,837,"Tallarico, Daniel",Daniel,Tallarico,–,1188,01:20:15,02:44:43,02:45:06
996,1048,997,838,"Loza, Bryan",Bryan,Loza,–,2420,01:22:37,02:44:43,02:45:39
997,1049,998,839,"Richer, Ryan",Ryan,Richer,–,2319,01:20:31,02:44:43,02:45:21
998,1050,999,840,"Miller, Gregory",Gregory,Miller,–,1088,01:21:26,02:44:43,02:45:00
999,1051,1000,841,"Wawszkowicz, Martin",Martin,Wawszkowicz,–,2730,01:21:57,02:44:43,02:45:27

In [83]:
person_dicts = []
for x in range(1,round(15176/25)) :
    print('dicts length',len(person_dicts))
    
    URL2 = f"""
https://results.baa.org/2023/?page={x}&event=R&event_main_group=runner&num_results=1000
&pid=list&pidp=start&search%5Bsex%5D=W
&search%5Bage_class%5D=%25&event=R&favorite_remove=9TGHS6FF181D5A#
"""
    r = requests.get(URL2) 
  
    soup = BeautifulSoup(r.content, 'html.parser')
    # for row in soup.find_all('div'):
    #     print(row.get_text())

    table = soup.find_all('div',class_="row")[1:2][0]
    rows = table.find_all('div',class_="row")[1:]
    print(len(rows))

    for row_ind in range(3,len(rows),3):#len(rows),3):
       # try :
        if row_ind + 2 < len(rows) :
            person_dict = {}
            names_row = rows[row_ind].get_text().strip().split('\n')
            person_dict['Place Overall'] = names_row[0]
            person_dict['Place Gender'] = names_row[1]
            person_dict['Place Division'] = names_row[2]
            person_dict['full_name'] = names_row[-1]
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

            person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = rows[row_ind + 1].get_text().strip().split('\n')[1][3:]
            times = rows[row_ind + 2].get_text().strip().split('\n')
            person_dict['half_marathon_split'] = times[0][4:]
            person_dict['full_split'] = times[1][10:]
            person_dict['finish_gun_time'] = times[2][10:]
            #print(row_ind,rows[row_ind].get_text())
            person_dicts.append(person_dict)
#         except :
#             #rint(rows[row_ind])
    
#             #print(rows[row_ind])
#person_dicts
df_boston_2023_2 = pd.DataFrame.from_dict(person_dicts)
df_boston_2023_2

dicts length 0
79
dicts length 25
79
dicts length 50
79
dicts length 75
79
dicts length 100
79
dicts length 125
79
dicts length 150
79
dicts length 175
79
dicts length 200
79
dicts length 225
79
dicts length 250
79
dicts length 275
79
dicts length 300
79
dicts length 325
79
dicts length 350
79
dicts length 375
79
dicts length 400
79
dicts length 425
79
dicts length 450
79
dicts length 475
79
dicts length 500
79
dicts length 525
79
dicts length 550
79
dicts length 575
79
dicts length 600
79
dicts length 625
79
dicts length 650
79
dicts length 675
79
dicts length 700
79
dicts length 725
79
dicts length 750
79
dicts length 775
79
dicts length 800
79
dicts length 825
79
dicts length 850
79
dicts length 875
79
dicts length 900
79
dicts length 925
79
dicts length 950
79
dicts length 975
79
dicts length 1000
79
dicts length 1025
79
dicts length 1050
79
dicts length 1075
79
dicts length 1100
79
dicts length 1125
79
dicts length 1150
79
dicts length 1175
79
dicts length 1200
79
dicts length 1225
79
dicts length 1250
79
dicts length 1275
79
dicts length 1300
79
dicts length 1325
79
dicts length 1350
79
dicts length 1375
79
dicts length 1400
79
dicts length 1425
79
dicts length 1450
79
dicts length 1475
79
dicts length 1500
79
dicts length 1525
79
dicts length 1550
79
dicts length 1575
79
dicts length 1600
79
dicts length 1625
79
dicts length 1650
79
dicts length 1675
79
dicts length 1700
79
dicts length 1725
79
dicts length 1750
79
dicts length 1775
79
dicts length 1800
79
dicts length 1825
79
dicts length 1850
79
dicts length 1875
79
dicts length 1900
79
dicts length 1925
79
dicts length 1950
79
dicts length 1975
79
dicts length 2000
79
dicts length 2025
79
dicts length 2050
79
dicts length 2075
79
dicts length 2100
79
dicts length 2125
79
dicts length 2150
79
dicts length 2175
79
dicts length 2200
79
dicts length 2225
79
dicts length 2250
79
dicts length 2275
79
dicts length 2300
79
dicts length 2325
79
dicts length 2350
79
dicts length 2375
79
dicts length 2400
79
dicts length 2425
79
dicts length 2450
79
dicts length 2475
79
dicts length 2500
79
dicts length 2525
79
dicts length 2550
79
dicts length 2575
79
dicts length 2600
79
dicts length 2625
79
dicts length 2650
79
dicts length 2675
79
dicts length 2700
79
dicts length 2725
79
dicts length 2750
79
dicts length 2775
79
dicts length 2800
79
dicts length 2825
79
dicts length 2850
79
dicts length 2875
79
dicts length 2900
79
dicts length 2925
79
dicts length 2950
79
dicts length 2975
79
dicts length 3000
79
dicts length 3025
79
dicts length 3050
79
dicts length 3075
79
dicts length 3100
79
dicts length 3125
79
dicts length 3150
79
dicts length 3175
79
dicts length 3200
79
dicts length 3225
79
dicts length 3250
79
dicts length 3275
79
dicts length 3300
79
dicts length 3325
79
dicts length 3350
79
dicts length 3375
79
dicts length 3400
79
dicts length 3425
79
dicts length 3450
79
dicts length 3475
79
dicts length 3500
79
dicts length 3525
79
dicts length 3550
79
dicts length 3575
79
dicts length 3600
79
dicts length 3625
79
dicts length 3650
79
dicts length 3675
79
dicts length 3700
79
dicts length 3725
79
dicts length 3750
79
dicts length 3775
79
dicts length 3800
79
dicts length 3825
79
dicts length 3850
79
dicts length 3875
79
dicts length 3900
79
dicts length 3925
79
dicts length 3950
79
dicts length 3975
79
dicts length 4000
79
dicts length 4025
79
dicts length 4050
79
dicts length 4075
79
dicts length 4100
79
dicts length 4125
79
dicts length 4150
79
dicts length 4175
79
dicts length 4200
79
dicts length 4225
79
dicts length 4250
79
dicts length 4275
79
dicts length 4300
79
dicts length 4325
79
dicts length 4350
79
dicts length 4375
79
dicts length 4400
79
dicts length 4425
79
dicts length 4450
79
dicts length 4475
79
dicts length 4500
79
dicts length 4525
79
dicts length 4550
79
dicts length 4575
79
dicts length 4600
79
dicts length 4625
79
dicts length 4650
79
dicts length 4675
79
dicts length 4700
79
dicts length 4725
79
dicts length 4750
79
dicts length 4775
79
dicts length 4800
79
dicts length 4825
79
dicts length 4850
79
dicts length 4875
79
dicts length 4900
79
dicts length 4925
79
dicts length 4950
79
dicts length 4975
79
dicts length 5000
79
dicts length 5025
79
dicts length 5050
79
dicts length 5075
79
dicts length 5100
79
dicts length 5125
79
dicts length 5150
79
dicts length 5175
79
dicts length 5200
79
dicts length 5225
79
dicts length 5250
79
dicts length 5275
79
dicts length 5300
79
dicts length 5325
79
dicts length 5350
79
dicts length 5375
79
dicts length 5400
79
dicts length 5425
79
dicts length 5450
79
dicts length 5475
79
dicts length 5500
79
dicts length 5525
79
dicts length 5550
79
dicts length 5575
79
dicts length 5600
79
dicts length 5625
79
dicts length 5650
79
dicts length 5675
79
dicts length 5700
79
dicts length 5725
79
dicts length 5750
79
dicts length 5775
79
dicts length 5800
79
dicts length 5825
79
dicts length 5850
79
dicts length 5875
79
dicts length 5900
79
dicts length 5925
79
dicts length 5950
79
dicts length 5975
79
dicts length 6000
79
dicts length 6025
79
dicts length 6050
79
dicts length 6075
79
dicts length 6100
79
dicts length 6125
79
dicts length 6150
79
dicts length 6175
79
dicts length 6200
79
dicts length 6225
79
dicts length 6250
79
dicts length 6275
79
dicts length 6300
79
dicts length 6325
79
dicts length 6350
79
dicts length 6375
79
dicts length 6400
79
dicts length 6425
79
dicts length 6450
79
dicts length 6475
79
dicts length 6500
79
dicts length 6525
79
dicts length 6550
79
dicts length 6575
79
dicts length 6600
79
dicts length 6625
79
dicts length 6650
79
dicts length 6675
79
dicts length 6700
79
dicts length 6725
79
dicts length 6750
79
dicts length 6775
79
dicts length 6800
79
dicts length 6825
79
dicts length 6850
79
dicts length 6875
79
dicts length 6900
79
dicts length 6925
79
dicts length 6950
79
dicts length 6975
79
dicts length 7000
79
dicts length 7025
79
dicts length 7050
79
dicts length 7075
79
dicts length 7100
79
dicts length 7125
79
dicts length 7150
79
dicts length 7175
79
dicts length 7200
79
dicts length 7225
79
dicts length 7250
79
dicts length 7275
79
dicts length 7300
79
dicts length 7325
79
dicts length 7350
79
dicts length 7375
79
dicts length 7400
79
dicts length 7425
79
dicts length 7450
79
dicts length 7475
79
dicts length 7500
79
dicts length 7525
79
dicts length 7550
79
dicts length 7575
79
dicts length 7600
79
dicts length 7625
79
dicts length 7650
79
dicts length 7675
79
dicts length 7700
79
dicts length 7725
79
dicts length 7750
79
dicts length 7775
79
dicts length 7800
79
dicts length 7825
79
dicts length 7850
79
dicts length 7875
79
dicts length 7900
79
dicts length 7925
79
dicts length 7950
79
dicts length 7975
79
dicts length 8000
79
dicts length 8025
79
dicts length 8050
79
dicts length 8075
79
dicts length 8100
79
dicts length 8125
79
dicts length 8150
79
dicts length 8175
79
dicts length 8200
79
dicts length 8225
79
dicts length 8250
79
dicts length 8275
79
dicts length 8300
79
dicts length 8325
79
dicts length 8350
79
dicts length 8375
79
dicts length 8400
79
dicts length 8425
79
dicts length 8450
79
dicts length 8475
79
dicts length 8500
79
dicts length 8525
79
dicts length 8550
79
dicts length 8575
79
dicts length 8600
79
dicts length 8625
79
dicts length 8650
79
dicts length 8675
79
dicts length 8700
79
dicts length 8725
79
dicts length 8750
79
dicts length 8775
79
dicts length 8800
79
dicts length 8825
79
dicts length 8850
79
dicts length 8875
79
dicts length 8900
79
dicts length 8925
79
dicts length 8950
79
dicts length 8975
79
dicts length 9000
79
dicts length 9025
79
dicts length 9050
79
dicts length 9075
79
dicts length 9100
79
dicts length 9125
79
dicts length 9150
79
dicts length 9175
79
dicts length 9200
79
dicts length 9225
79
dicts length 9250
79
dicts length 9275
79
dicts length 9300
79
dicts length 9325
79
dicts length 9350
79
dicts length 9375
79
dicts length 9400
79
dicts length 9425
79
dicts length 9450
79
dicts length 9475
79
dicts length 9500
79
dicts length 9525
79
dicts length 9550
79
dicts length 9575
79
dicts length 9600
79
dicts length 9625
79
dicts length 9650
79
dicts length 9675
79
dicts length 9700
79
dicts length 9725
79
dicts length 9750
79
dicts length 9775
79
dicts length 9800

79
dicts length 9825
79
dicts length 9850
79
dicts length 9875
79
dicts length 9900
79
dicts length 9925
79
dicts length 9950
79
dicts length 9975
79
dicts length 10000
79
dicts length 10025
79
dicts length 10050
79
dicts length 10075
79
dicts length 10100
79
dicts length 10125
79
dicts length 10150
79
dicts length 10175
79
dicts length 10200
79
dicts length 10225
79
dicts length 10250
79
dicts length 10275
79
dicts length 10300
79
dicts length 10325
79
dicts length 10350
79
dicts length 10375
79
dicts length 10400
79
dicts length 10425
79
dicts length 10450
79
dicts length 10475
79
dicts length 10500
79
dicts length 10525
79
dicts length 10550
79
dicts length 10575
79
dicts length 10600
79
dicts length 10625
79
dicts length 10650
79
dicts length 10675
79
dicts length 10700
79
dicts length 10725
79
dicts length 10750
79
dicts length 10775
79
dicts length 10800
79
dicts length 10825
79
dicts length 10850
79
dicts length 10875
79
dicts length 10900
79
dicts length 10925
79
dicts length 10950
79
dicts length 10975
79
dicts length 11000
79
dicts length 11025
79
dicts length 11050
79
dicts length 11075
79
dicts length 11100
79
dicts length 11125
79
dicts length 11150
79
dicts length 11175
79
dicts length 11200
79
dicts length 11225
79
dicts length 11250
79
dicts length 11275
79
dicts length 11300
79
dicts length 11325
79
dicts length 11350
79
dicts length 11375
79
dicts length 11400
79
dicts length 11425
79
dicts length 11450
79
dicts length 11475
79
dicts length 11500
79
dicts length 11525
79
dicts length 11550
79
dicts length 11575
79
dicts length 11600
79
dicts length 11625
79
dicts length 11650
79
dicts length 11675
79
dicts length 11700
79
dicts length 11725
79
dicts length 11750
79
dicts length 11775
79
dicts length 11800
79
dicts length 11825
79
dicts length 11850
79
dicts length 11875
79
dicts length 11900
79
dicts length 11925
79
dicts length 11950
79
dicts length 11975
79
dicts length 12000
79
dicts length 12025
79
dicts length 12050
79
dicts length 12075
79
dicts length 12100
79
dicts length 12125
79
dicts length 12150
79
dicts length 12175
79
dicts length 12200
79
dicts length 12225
79
dicts length 12250
79
dicts length 12275
79
dicts length 12300
79
dicts length 12325
79
dicts length 12350
79
dicts length 12375
79
dicts length 12400
79
dicts length 12425
79
dicts length 12450
79
dicts length 12475
79
dicts length 12500
79
dicts length 12525
79
dicts length 12550
79
dicts length 12575
79
dicts length 12600
79
dicts length 12625
79
dicts length 12650
79
dicts length 12675
79
dicts length 12700
79
dicts length 12725
79
dicts length 12750
79
dicts length 12775
79
dicts length 12800
79
dicts length 12825
79
dicts length 12850
79
dicts length 12875
79
dicts length 12900
79
dicts length 12925
79
dicts length 12950
79
dicts length 12975
79
dicts length 13000
79
dicts length 13025
79
dicts length 13050
79
dicts length 13075
79
dicts length 13100
79
dicts length 13125
79
dicts length 13150
79
dicts length 13175
79
dicts length 13200
79
dicts length 13225
79
dicts length 13250
79
dicts length 13275
79
dicts length 13300
79
dicts length 13325
79
dicts length 13350
79
dicts length 13375
79
dicts length 13400
79
dicts length 13425
79
dicts length 13450
79
dicts length 13475
79
dicts length 13500
79
dicts length 13525
79
dicts length 13550
79
dicts length 13575
79
dicts length 13600
79
dicts length 13625
79
dicts length 13650
79
dicts length 13675
79
dicts length 13700
79
dicts length 13725
79
dicts length 13750
79
dicts length 13775
79
dicts length 13800
79
dicts length 13825
79
dicts length 13850
79
dicts length 13875
79
dicts length 13900
79
dicts length 13925
79
dicts length 13950
79
dicts length 13975
79
dicts length 14000
79
dicts length 14025
79
dicts length 14050
79
dicts length 14075
79
dicts length 14100
79
dicts length 14125
79
dicts length 14150
79
dicts length 14175
79
dicts length 14200
79
dicts length 14225
79
dicts length 14250
79
dicts length 14275
79
dicts length 14300
79
dicts length 14325
79
dicts length 14350
79
dicts length 14375
79
dicts length 14400
79
dicts length 14425
79
dicts length 14450
79
dicts length 14475
79
dicts length 14500
79
dicts length 14525
79
dicts length 14550
79
dicts length 14575
79
dicts length 14600
79
dicts length 14625
79
dicts length 14650
79
dicts length 14675
79
dicts length 14700
79
dicts length 14725
79
dicts length 14750
79
dicts length 14775
79
dicts length 14800
79
dicts length 14825
79
dicts length 14850
79
dicts length 14875
79
dicts length 14900
79
dicts length 14925
79
dicts length 14950
79
dicts length 14975
79
dicts length 15000
79
dicts length 15025
79
dicts length 15050
79
dicts length 15075
79
dicts length 15100
79
dicts length 15125
79

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,1,1,1,"Chebet, Evans",Evans,Chebet,–,1,01:02:20,02:05:54,02:05:54
1,2,2,2,"Geay, Gabriel",Gabriel,Geay,–,3,01:02:20,02:06:04,02:06:04
2,3,3,3,"Kipruto, Benson",Benson,Kipruto,–,5,01:02:19,02:06:06,02:06:06
3,4,4,4,"Korir, Albert",Albert,Korir,–,19,01:02:20,02:08:01,02:08:01
4,5,5,5,"Talbi, Zouhair",Zouhair,Talbi,–,31,01:02:20,02:08:35,02:08:35
...,...,...,...,...,...,...,...,...,...,...,...
15145,26568,15147,1420,"Keady, Michael",Michael,Keady,–,29627,02:41:27,06:04:10,06:09:23
15146,26571,15148,5285,"Raymond, Lee",Lee,Raymond,–,25897,02:48:23,06:04:41,06:05:16
15147,26572,15149,546,"Murphy, Terry",Terry,Murphy,–,25745,02:34:32,06:04:43,06:05:46
15148,26574,15150,2249,"Pilz, Thorsten",Thorsten,Pilz,–,13768,02:48:05,06:04:49,06:08:21
15149,26575,15151,2048,"Allens, Shamarlas",Shamarlas,Allens,–,27424,02:56:56,06:05:03,06:07:47

In [92]:
person_dicts = []
for x in range(round(15150/25),round(15250/25)) :
    print('dicts length',len(person_dicts))
    
    URL3 = f"""
https://results.baa.org/2023/?page={x}&event=R&event_main_group=runner&num_results=25
&pid=list&pidp=start&search%5Bsex%5D=M
&search%5Bage_class%5D=%25&event=R&favorite_remove=9TGHS6FF181D5A#
"""
    r = requests.get(URL3) 
  
    soup = BeautifulSoup(r.content, 'html.parser')
    # for row in soup.find_all('div'):
    #     print(row.get_text())

    table = soup.find_all('div',class_="row")[1:2][0]
    rows = table.find_all('div',class_="row")[1:]
    print(len(rows))

    for row_ind in range(3,len(rows),3):#len(rows),3):
       # try :
        if row_ind + 2 < len(rows) :
            person_dict = {}
            names_row = rows[row_ind].get_text().strip().split('\n')
            person_dict['Place Overall'] = names_row[0]
            person_dict['Place Gender'] = names_row[1]
            person_dict['Place Division'] = names_row[2]
            person_dict['full_name'] = names_row[-1]
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

            person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = rows[row_ind + 1].get_text().strip().split('\n')[1][3:]
            times = rows[row_ind + 2].get_text().strip().split('\n')
            person_dict['half_marathon_split'] = times[0][4:]
            person_dict['full_split'] = times[1][10:]
            person_dict['finish_gun_time'] = times[2][10:]
            #print(row_ind,rows[row_ind].get_text())
            person_dicts.append(person_dict)
#         except :
#             #rint(rows[row_ind])
    
#             #print(rows[row_ind])
#person_dicts
df_boston_2023_3 = pd.DataFrame.from_dict(person_dicts)
df_boston_2023_3

dicts length 0
79
dicts length 25
79
dicts length 50
7
dicts length 51
4

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,26522,15127,542,"Buslau, Klaus",Klaus,Buslau,–,31696,02:42:06,06:00:06,06:04:52
1,26526,15128,2248,"Kayser, David",David,Kayser,–,29074,02:46:16,06:00:18,06:02:57
2,26529,15129,1416,"Hong, Tin",Tin,Hong,–,24785,03:04:41,06:00:25,06:10:17
3,26531,15130,5283,"Knowles, Ben",Ben,Knowles,–,30666,02:41:32,06:00:41,06:03:37
4,26532,15131,1417,"Tindall, Paul",Paul,Tindall,–,25647,02:48:21,06:00:48,06:01:53
5,26536,15132,1103,"Egan, Jack",Jack,Egan,Empire One Running Club,27773,02:54:04,06:01:14,06:05:27
6,26539,15133,543,"Brown, John",John,Brown,–,15856,02:42:59,06:01:42,06:09:38
7,26540,15134,2240,"Iqbal, Shams",Shams,Iqbal,–,26734,03:14:12,06:01:45,06:01:45
8,26541,15135,1104,"Carlson, Tony",Tony,Carlson,–,30189,02:42:02,06:01:49,06:04:50
9,26543,15136,1105,"Stewart, Peter",Peter,Stewart,–,30895,02:30:38,06:02:04,06:05:56
10,26544,15137,544,"Dequintal, Ray",Ray,Dequintal,–,25516,02:54:07,06:02:11,06:02:43
11,26550,15138,1106,"Gibbons, Ronald",Ronald,Gibbons,–,29694,02:50:29,06:02:32,06:07:47
12,26551,15139,1418,"Brown, Christopher",Christopher,Brown,–,30164,02:50:34,06:02:32,06:07:47
13,26552,15140,2045,"Sardinha, Emanuel",Emanuel,Sardinha,–,25096,02:50:32,06:02:35,06:07:48
14,26555,15141,5284,"Larovere, Francis",Francis,Larovere,–,25463,02:46:04,06:02:44,06:09:52
15,26560,15142,2046,"Lee, Kwok Kee",Kwok Kee,Lee,–,30948,02:49:09,06:03:21,06:08:12
16,26561,15143,1419,"Colby, Christopher",Christopher,Colby,–,17919,02:57:13,06:03:23,06:04:17
17,26562,15144,545,"Keeffe, David",David,Keeffe,–,15951,02:53:46,06:03:25,06:08:50
18,26564,15145,208,"Sikora, Joseph",Joseph,Sikora,–,15960,02:54:18,06:03:46,06:08:39
19,26565,15146,2047,"Pina, Jason",Jason,Pina,–,27533,02:45:34,06:03:47,06:06:12
20,26568,15147,1420,"Keady, Michael",Michael,Keady,–,29627,02:41:27,06:04:10,06:09:23
21,26571,15148,5285,"Raymond, Lee",Lee,Raymond,–,25897,02:48:23,06:04:41,06:05:16
22,26572,15149,546,"Murphy, Terry",Terry,Murphy,–,25745,02:34:32,06:04:43,06:05:46
23,26574,15150,2249,"Pilz, Thorsten",Thorsten,Pilz,–,13768,02:48:05,06:04:49,06:08:21
24,26575,15151,2048,"Allens, Shamarlas",Shamarlas,Allens,–,27424,02:56:56,06:05:03,06:07:47
25,26578,15152,209,"Chamnankool, Vorawit",Vorawit,Chamnankool,–,30646,02:50:07,06:05:16,06:08:30
26,26581,15153,1421,"Curl, Tony",Tony,Curl,–,31078,02:48:19,06:05:36,06:10:05
27,26586,15154,5286,"Harris, Michael",Michael,Harris,–,26719,02:42:53,06:06:43,06:10:40
28,26589,15155,47,"Kennedy, Bob",Bob,Kennedy,New England 65+ Runners Club,24001,03:02:38,06:08:21,06:10:55
29,26592,15156,2250,"Leslie, Michael",Michael,Leslie,Notch Brewing Runners,24728,02:53:25,06:08:29,06:08:44
30,26593,15157,547,"Brady Iii, Arthur",Arthur,Brady Iii,–,22442,02:15:19,06:08:40,06:12:25
31,26594,15158,1107,"Lukenbill, Francis",Francis,Lukenbill,–,30536,02:59:05,06:08:50,06:09:38
32,26596,15159,2251,"Tiongco, Gene Gerald",Gene Gerald,Tiongco,–,29493,02:49:54,06:09:06,06:09:48
33,26597,15160,48,"Geary, James",James,Geary,–,15956,03:00:00,06:09:47,06:14:44
34,26601,15161,49,"Gless, Gerard",Gerard,Gless,–,27751,02:57:18,06:11:58,06:15:51
35,26602,15162,210,"Chen, Wern Jyh",Wern Jyh,Chen,–,23660,02:56:08,06:13:34,06:16:50
36,26604,15163,2252,"Wong, Benton",Benton,Wong,–,3553,02:49:33,06:16:56,06:21:07
37,26605,15164,1108,"Bergin, Matthew",Matthew,Bergin,–,15965,02:46:26,06:18:22,06:24:10
38,26606,15165,211,"Burrows, Stephen",Stephen,Burrows,–,15954,02:57:12,06:18:32,06:24:28
39,26608,15166,1109,"Strider, Scott",Scott,Strider,–,15944,02:58:29,06:21:11,06:24:37
40,26609,15167,2049,"Hoffman, Tom",Tom,Hoffman,–,14927,03:14:24,06:24:09,06:28:29
41,26612,15168,212,"Warde, Kenneth",Kenneth,Warde,–,15940,02:58:51,06:28:26,06:33:22
42,26614,15169,548,"Edwards, John",John,Edwards,–,29525,02:59:55,06:31:54,06:34:24
43,26615,15170,213,"Langevin, William",William,Langevin,–,15963,03:02:52,06:34:01,06:40:40
44,26616,15171,549,"Ottaviano, Gerard",Gerard,Ottaviano,Greater Lowell Road Runners,15964,–,06:34:15,06:39:32
45,26617,15172,1422,"Audet, David",David,Audet,–,15878,02:44:32,06:37:45,06:43:04
46,26618,15173,1110,"Solberg, Bryon",Bryon,Solberg,–,7518,03:11:17,06:38:59,06:45:28
47,26619,15174,2050,"Davidson, Jonathan",Jonathan,Davidson,–,7520,02:39:22,06:40:56,06:47:13
48,26620,15175,2241,"Arai, Tatsuya",Tatsuya,Arai,–,3220,03:05:18,06:43:08,06:44:56
49,26622,15176,2051,"Weisberg, Scott",Scott,Weisberg,–,7593,03:27:15,07:04:20,07:10:42
50,26623,15177,2052,"Burros, Aaron",Aaron,Burros,–,7544,03:18:08,07:13:39,07:19:57

In [97]:
df_2023_mens_total = pd.concat([df_boston_2023_2,df_boston_2023_3],ignore_index=True)
df_2023_mens_total

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,1,1,1,"Chebet, Evans",Evans,Chebet,–,1,01:02:20,02:05:54,02:05:54
1,2,2,2,"Geay, Gabriel",Gabriel,Geay,–,3,01:02:20,02:06:04,02:06:04
2,3,3,3,"Kipruto, Benson",Benson,Kipruto,–,5,01:02:19,02:06:06,02:06:06
3,4,4,4,"Korir, Albert",Albert,Korir,–,19,01:02:20,02:08:01,02:08:01
4,5,5,5,"Talbi, Zouhair",Zouhair,Talbi,–,31,01:02:20,02:08:35,02:08:35
...,...,...,...,...,...,...,...,...,...,...,...
15171,26618,15173,1110,"Solberg, Bryon",Bryon,Solberg,–,7518,03:11:17,06:38:59,06:45:28
15172,26619,15174,2050,"Davidson, Jonathan",Jonathan,Davidson,–,7520,02:39:22,06:40:56,06:47:13
15173,26620,15175,2241,"Arai, Tatsuya",Tatsuya,Arai,–,3220,03:05:18,06:43:08,06:44:56
15174,26622,15176,2051,"Weisberg, Scott",Scott,Weisberg,–,7593,03:27:15,07:04:20,07:10:42
15175,26623,15177,2052,"Burros, Aaron",Aaron,Burros,–,7544,03:18:08,07:13:39,07:19:57

In [108]:
df_2023_mens_total.to_csv('boston_marathon_results_2023_mens.csv')

WOMENS

In [ ]:
person_dicts = []
for x in range(1,round(15176/25)) :
    print('dicts length',len(person_dicts))
    
    URL2 = f"""
https://results.baa.org/2023/?page={x}&event=R&event_main_group=runner&num_results=1000
&pid=list&pidp=start&search%5Bsex%5D=W
&search%5Bage_class%5D=%25&event=R&favorite_remove=9TGHS6FF181D5A#
"""
    r = requests.get(URL2) 
  
    soup = BeautifulSoup(r.content, 'html.parser')
    # for row in soup.find_all('div'):
    #     print(row.get_text())

    table = soup.find_all('div',class_="row")[1:2][0]
    rows = table.find_all('div',class_="row")[1:]
    print(len(rows))

    for row_ind in range(3,len(rows),3):#len(rows),3):
       # try :
        if row_ind + 2 < len(rows) :
            person_dict = {}
            names_row = rows[row_ind].get_text().strip().split('\n')
            person_dict['Place Overall'] = names_row[0]
            person_dict['Place Gender'] = names_row[1]
            person_dict['Place Division'] = names_row[2]
            person_dict['full_name'] = names_row[-1]
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

            person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = rows[row_ind + 1].get_text().strip().split('\n')[1][3:]
            times = rows[row_ind + 2].get_text().strip().split('\n')
            person_dict['half_marathon_split'] = times[0][4:]
            person_dict['full_split'] = times[1][10:]
            person_dict['finish_gun_time'] = times[2][10:]
            #print(row_ind,rows[row_ind].get_text())
            person_dicts.append(person_dict)
#         except :
#             #rint(rows[row_ind])
    
#             #print(rows[row_ind])
#person_dicts
df_boston_2023_2 = pd.DataFrame.from_dict(person_dicts)
df_boston_2023_2

### 2022

In [115]:
person_dicts = []
for x in range(1,round(14400/25)) :#round(14261/25)) :
    print('dicts length',len(person_dicts))
    
    URL2 = f"""
https://results.baa.org/2022/?page={x}&event=R&event_main_group=runner&num_results=1000
&pid=list&pidp=start&search%5Bsex%5D=M
&search%5Bage_class%5D=%25&event=R&favorite_remove=9TGHS6FF181D5A#
"""
    r = requests.get(URL2) 
  
    soup = BeautifulSoup(r.content, 'html.parser')
    # for row in soup.find_all('div'):
    #     print(row.get_text())

    table = soup.find_all('div',class_="row")[1:2][0]
    rows = table.find_all('div',class_="row")[1:]
    print(len(rows))

    for row_ind in range(3,len(rows),3):#len(rows),3):
       # try :
        if row_ind + 2 < len(rows) :
            person_dict = {}
            names_row = rows[row_ind].get_text().strip().split('\n')
            person_dict['Place Overall'] = names_row[0]
            person_dict['Place Gender'] = names_row[1]
            person_dict['Place Division'] = names_row[2]
            person_dict['full_name'] = names_row[-1]
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip().split('(')[0]
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
                if len(person_dict['full_name'].split('(')) > 1 :
                    person_dict['country'] = person_dict['full_name'].split('(')[1].strip()[:-1]
                else :
                    person_dict['country'] = None
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

            person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = rows[row_ind + 1].get_text().strip().split('\n')[1][3:]
            times = rows[row_ind + 2].get_text().strip().split('\n')
            person_dict['half_marathon_split'] = times[0][4:]
            person_dict['full_split'] = times[1][10:]
            person_dict['finish_gun_time'] = times[2][10:]
            #print(row_ind,rows[row_ind].get_text())
            person_dicts.append(person_dict)
#         except :
#             #rint(rows[row_ind])
    
#             #print(rows[row_ind])
#person_dicts
df_boston_2022_1 = pd.DataFrame.from_dict(person_dicts)
df_boston_2022_1

dicts length 0
79
dicts length 25
79
dicts length 50
79
dicts length 75
79
dicts length 100
79
dicts length 125
79
dicts length 150
79
dicts length 175
79
dicts length 200
79
dicts length 225
79
dicts length 250
79
dicts length 275
79
dicts length 300
79
dicts length 325
79
dicts length 350
79
dicts length 375
79
dicts length 400
79
dicts length 425
79
dicts length 450
79
dicts length 475
79
dicts length 500
79
dicts length 525
79
dicts length 550
79
dicts length 575
79
dicts length 600
79
dicts length 625
79
dicts length 650
79
dicts length 675
79
dicts length 700
79
dicts length 725
79
dicts length 750
79
dicts length 775
79
dicts length 800
79
dicts length 825
79
dicts length 850
79
dicts length 875
79
dicts length 900
79
dicts length 925
79
dicts length 950
79
dicts length 975
79
dicts length 1000
79
dicts length 1025
79
dicts length 1050
79
dicts length 1075
79
dicts length 1100
79
dicts length 1125
79
dicts length 1150
79
dicts length 1175
79
dicts length 1200
79
dicts length 1225
79
dicts length 1250
79
dicts length 1275
79
dicts length 1300
79
dicts length 1325
79
dicts length 1350
79
dicts length 1375
79
dicts length 1400
79
dicts length 1425
79
dicts length 1450
79
dicts length 1475
79
dicts length 1500
79
dicts length 1525
79
dicts length 1550
79
dicts length 1575
79
dicts length 1600
79
dicts length 1625
79
dicts length 1650
79
dicts length 1675
79
dicts length 1700
79
dicts length 1725
79
dicts length 1750
79
dicts length 1775
79
dicts length 1800
79
dicts length 1825
79
dicts length 1850
79
dicts length 1875
79
dicts length 1900
79
dicts length 1925
79
dicts length 1950
79
dicts length 1975
79
dicts length 2000
79
dicts length 2025
79
dicts length 2050
79
dicts length 2075
79
dicts length 2100
79
dicts length 2125
79
dicts length 2150
79
dicts length 2175
79
dicts length 2200
79
dicts length 2225
79
dicts length 2250
79
dicts length 2275
79
dicts length 2300
79
dicts length 2325
79
dicts length 2350
79
dicts length 2375
79
dicts length 2400
79
dicts length 2425
79
dicts length 2450
79
dicts length 2475
79
dicts length 2500
79
dicts length 2525
79
dicts length 2550
79
dicts length 2575
79
dicts length 2600
79
dicts length 2625
79
dicts length 2650
79
dicts length 2675
79
dicts length 2700
79
dicts length 2725
79
dicts length 2750
79
dicts length 2775
79
dicts length 2800
79
dicts length 2825
79
dicts length 2850
79
dicts length 2875
79
dicts length 2900
79
dicts length 2925
79
dicts length 2950
79
dicts length 2975
79
dicts length 3000
79
dicts length 3025
79
dicts length 3050
79
dicts length 3075
79
dicts length 3100
79
dicts length 3125
79
dicts length 3150
79
dicts length 3175
79
dicts length 3200
79
dicts length 3225
79
dicts length 3250
79
dicts length 3275
79
dicts length 3300
79
dicts length 3325
79
dicts length 3350
79
dicts length 3375
79
dicts length 3400
79
dicts length 3425
79
dicts length 3450
79
dicts length 3475
79
dicts length 3500
79
dicts length 3525
79
dicts length 3550
79
dicts length 3575
79
dicts length 3600
79
dicts length 3625
79
dicts length 3650
79
dicts length 3675
79
dicts length 3700
79
dicts length 3725
79
dicts length 3750
79
dicts length 3775
79
dicts length 3800
79
dicts length 3825
79
dicts length 3850
79
dicts length 3875
79
dicts length 3900
79
dicts length 3925
79
dicts length 3950
79
dicts length 3975
79
dicts length 4000
79
dicts length 4025
79
dicts length 4050
79
dicts length 4075
79
dicts length 4100
79
dicts length 4125
79
dicts length 4150
79
dicts length 4175
79
dicts length 4200
79
dicts length 4225
79
dicts length 4250
79
dicts length 4275
79
dicts length 4300
79
dicts length 4325
79
dicts length 4350
79
dicts length 4375
79
dicts length 4400
79
dicts length 4425
79
dicts length 4450
79
dicts length 4475
79
dicts length 4500
79
dicts length 4525
79
dicts length 4550
79
dicts length 4575
79
dicts length 4600
79
dicts length 4625
79
dicts length 4650
79
dicts length 4675
79
dicts length 4700
79
dicts length 4725
79
dicts length 4750
79
dicts length 4775
79
dicts length 4800
79
dicts length 4825
79
dicts length 4850
79
dicts length 4875
79
dicts length 4900
79
dicts length 4925
79
dicts length 4950
79
dicts length 4975
79
dicts length 5000
79
dicts length 5025
79
dicts length 5050
79
dicts length 5075
79
dicts length 5100
79
dicts length 5125
79
dicts length 5150
79
dicts length 5175
79
dicts length 5200
79
dicts length 5225
79
dicts length 5250
79
dicts length 5275
79
dicts length 5300
79
dicts length 5325
79
dicts length 5350
79
dicts length 5375
79
dicts length 5400
79
dicts length 5425
79
dicts length 5450
79
dicts length 5475
79
dicts length 5500
79
dicts length 5525
79
dicts length 5550
79
dicts length 5575
79
dicts length 5600
79
dicts length 5625
79
dicts length 5650
79
dicts length 5675
79
dicts length 5700
79
dicts length 5725
79
dicts length 5750
79
dicts length 5775
79
dicts length 5800
79
dicts length 5825
79
dicts length 5850
79
dicts length 5875
79
dicts length 5900
79
dicts length 5925
79
dicts length 5950
79
dicts length 5975
79
dicts length 6000
79
dicts length 6025
79
dicts length 6050
79
dicts length 6075
79
dicts length 6100
79
dicts length 6125
79
dicts length 6150
79
dicts length 6175
79
dicts length 6200
79
dicts length 6225
79
dicts length 6250
79
dicts length 6275
79
dicts length 6300
79
dicts length 6325
79
dicts length 6350
79
dicts length 6375
79
dicts length 6400
79
dicts length 6425
79
dicts length 6450
79
dicts length 6475
79
dicts length 6500
79
dicts length 6525
79
dicts length 6550
79
dicts length 6575
79
dicts length 6600
79
dicts length 6625
79
dicts length 6650
79
dicts length 6675
79
dicts length 6700
79
dicts length 6725
79
dicts length 6750
79
dicts length 6775
79
dicts length 6800
79
dicts length 6825
79
dicts length 6850
79
dicts length 6875
79
dicts length 6900
79
dicts length 6925
79
dicts length 6950
79
dicts length 6975
79
dicts length 7000
79
dicts length 7025
79
dicts length 7050
79
dicts length 7075
79
dicts length 7100
79
dicts length 7125
79
dicts length 7150
79
dicts length 7175
79
dicts length 7200
79
dicts length 7225
79
dicts length 7250
79
dicts length 7275
79
dicts length 7300
79
dicts length 7325
79
dicts length 7350
79
dicts length 7375
79
dicts length 7400
79
dicts length 7425
79
dicts length 7450
79
dicts length 7475
79
dicts length 7500
79
dicts length 7525
79
dicts length 7550
79
dicts length 7575
79
dicts length 7600
79
dicts length 7625
79
dicts length 7650
79
dicts length 7675
79
dicts length 7700
79
dicts length 7725
79
dicts length 7750
79
dicts length 7775
79
dicts length 7800
79
dicts length 7825
79
dicts length 7850
79
dicts length 7875
79
dicts length 7900
79
dicts length 7925
79
dicts length 7950
79
dicts length 7975
79
dicts length 8000
79
dicts length 8025
79
dicts length 8050
79
dicts length 8075
79
dicts length 8100
79
dicts length 8125
79
dicts length 8150
79
dicts length 8175
79
dicts length 8200
79
dicts length 8225
79
dicts length 8250
79
dicts length 8275
79
dicts length 8300
79
dicts length 8325
79
dicts length 8350
79
dicts length 8375
79
dicts length 8400
79
dicts length 8425
79
dicts length 8450
79
dicts length 8475
79
dicts length 8500
79
dicts length 8525
79
dicts length 8550
79
dicts length 8575
79
dicts length 8600
79
dicts length 8625
79
dicts length 8650
79
dicts length 8675
79
dicts length 8700
79
dicts length 8725
79
dicts length 8750
79
dicts length 8775
79
dicts length 8800
79
dicts length 8825
79
dicts length 8850
79
dicts length 8875
79
dicts length 8900
79
dicts length 8925
79
dicts length 8950
79
dicts length 8975
79
dicts length 9000
79
dicts length 9025
79
dicts length 9050
79
dicts length 9075
79
dicts length 9100
79
dicts length 9125
79
dicts length 9150
79
dicts length 9175
79
dicts length 9200
79
dicts length 9225
79
dicts length 9250
79
dicts length 9275
79
dicts length 9300
79
dicts length 9325
79
dicts length 9350
79
dicts length 9375
79
dicts length 9400
79
dicts length 9425
79
dicts length 9450
79
dicts length 9475
79
dicts length 9500
79
dicts length 9525
79
dicts length 9550
79
dicts length 9575
79
dicts length 9600
79
dicts length 9625
79
dicts length 9650
79
dicts length 9675
79
dicts length 9700
79
dicts length 9725
79
dicts length 9750
79
dicts length 9775
79
dicts length 9800

79
dicts length 9825
79
dicts length 9850
79
dicts length 9875
79
dicts length 9900
79
dicts length 9925
79
dicts length 9950
79
dicts length 9975
79
dicts length 10000
79
dicts length 10025
79
dicts length 10050
79
dicts length 10075
79
dicts length 10100
79
dicts length 10125
79
dicts length 10150
79
dicts length 10175
79
dicts length 10200
79
dicts length 10225
79
dicts length 10250
79
dicts length 10275
79
dicts length 10300
79
dicts length 10325
79
dicts length 10350
79
dicts length 10375
79
dicts length 10400
79
dicts length 10425
79
dicts length 10450
79
dicts length 10475
79
dicts length 10500
79
dicts length 10525
79
dicts length 10550
79
dicts length 10575
79
dicts length 10600
79
dicts length 10625
79
dicts length 10650
79
dicts length 10675
79
dicts length 10700
79
dicts length 10725
79
dicts length 10750
79
dicts length 10775
79
dicts length 10800
79
dicts length 10825
79
dicts length 10850
79
dicts length 10875
79
dicts length 10900
79
dicts length 10925
79
dicts length 10950
79
dicts length 10975
79
dicts length 11000
79
dicts length 11025
79
dicts length 11050
79
dicts length 11075
79
dicts length 11100
79
dicts length 11125
79
dicts length 11150
79
dicts length 11175
79
dicts length 11200
79
dicts length 11225
79
dicts length 11250
79
dicts length 11275
79
dicts length 11300
79
dicts length 11325
79
dicts length 11350
79
dicts length 11375
79
dicts length 11400
79
dicts length 11425
79
dicts length 11450
79
dicts length 11475
79
dicts length 11500
79
dicts length 11525
79
dicts length 11550
79
dicts length 11575
79
dicts length 11600
79
dicts length 11625
79
dicts length 11650
79
dicts length 11675
79
dicts length 11700
79
dicts length 11725
79
dicts length 11750
79
dicts length 11775
79
dicts length 11800
79
dicts length 11825
79
dicts length 11850
79
dicts length 11875
79
dicts length 11900
79
dicts length 11925
79
dicts length 11950
79
dicts length 11975
79
dicts length 12000
79
dicts length 12025
79
dicts length 12050
79
dicts length 12075
79
dicts length 12100
79
dicts length 12125
79
dicts length 12150
79
dicts length 12175
79
dicts length 12200
79
dicts length 12225
79
dicts length 12250
79
dicts length 12275
79
dicts length 12300
79
dicts length 12325
79
dicts length 12350
79
dicts length 12375
79
dicts length 12400
79
dicts length 12425
79
dicts length 12450
79
dicts length 12475
79
dicts length 12500
79
dicts length 12525
79
dicts length 12550
79
dicts length 12575
79
dicts length 12600
79
dicts length 12625
79
dicts length 12650
79
dicts length 12675
79
dicts length 12700
79
dicts length 12725
79
dicts length 12750
79
dicts length 12775
79
dicts length 12800
79
dicts length 12825
79
dicts length 12850
79
dicts length 12875
79
dicts length 12900
79
dicts length 12925
79
dicts length 12950
79
dicts length 12975
79
dicts length 13000
79
dicts length 13025
79
dicts length 13050
79
dicts length 13075
79
dicts length 13100
79
dicts length 13125
79
dicts length 13150
79
dicts length 13175
79
dicts length 13200
79
dicts length 13225
79
dicts length 13250
79
dicts length 13275
79
dicts length 13300
79
dicts length 13325
79
dicts length 13350
79
dicts length 13375
79
dicts length 13400
79
dicts length 13425
79
dicts length 13450
79
dicts length 13475
79
dicts length 13500
79
dicts length 13525
79
dicts length 13550
79
dicts length 13575
79
dicts length 13600
79
dicts length 13625
79
dicts length 13650
79
dicts length 13675
79
dicts length 13700
79
dicts length 13725
79
dicts length 13750
79
dicts length 13775
79
dicts length 13800
79
dicts length 13825
79
dicts length 13850
79
dicts length 13875
79
dicts length 13900
79
dicts length 13925
79
dicts length 13950
79
dicts length 13975
79
dicts length 14000
79
dicts length 14025
79
dicts length 14050
79
dicts length 14075
79
dicts length 14100
79
dicts length 14125
79
dicts length 14150
79
dicts length 14175
79
dicts length 14200
79
dicts length 14225
79
dicts length 14250
37
dicts length 14261
4
dicts length 14261
4
dicts length 14261
4
dicts length 14261
4

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,country,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,1,1,1,"Chebet, Evans (KEN)",Evans,Chebet,KEN,–,4,01:03:26,02:06:51,02:06:51
1,2,2,2,"Cherono, Lawrence (KEN)",Lawrence,Cherono,KEN,–,5,01:03:27,02:07:21,02:07:21
2,3,3,3,"Kipruto, Benson (KEN)",Benson,Kipruto,KEN,–,1,01:03:26,02:07:27,02:07:27
3,4,4,4,"Geay, Gabriel (TAN)",Gabriel,Geay,TAN,–,9,01:03:26,02:07:53,02:07:53
4,5,5,5,"Kiptanui, Eric (KEN)",Eric,Kiptanui,KEN,–,11,01:03:26,02:08:47,02:08:47
...,...,...,...,...,...,...,...,...,...,...,...,...
14256,24829,14257,1055,"Grossi, Anthony (USA)",Anthony,Grossi,USA,–,7658,03:00:39,06:55:49,07:02:00
14257,24830,14258,1451,"Kent, Paul (USA)",Paul,Kent,USA,–,7681,02:54:15,06:56:35,06:57:17
14258,24831,14259,1900,"Burros, Aaron (USA)",Aaron,Burros,USA,–,7638,03:04:52,06:58:12,07:04:14
14259,24832,14260,1056,"Martin Arjona, Julian (ESP)",Julian,Martin Arjona,ESP,–,28701,02:58:05,06:58:50,07:04:26
14260,24833,14261,4818,"Valenciano, Jorge (MEX)",Jorge,Valenciano,MEX,–,5398,03:19:31,07:01:32,07:04:53

In [116]:
df_boston_2022_1.to_csv('boston_marathon_results_2022_mens.csv')

In [118]:
person_dicts = []
for x in range(1,round(8050/25)) :#round(14261/25)) :
    print('dicts length',len(person_dicts))
    
    URL2 = f"""
https://results.baa.org/2021/?page={x}&event=R&event_main_group=runner&num_results=1000
&pid=list&pidp=start&search%5Bsex%5D=M
&search%5Bage_class%5D=%25&event=R&favorite_remove=9TGHS6FF181D5A#
"""
    r = requests.get(URL2) 
  
    soup = BeautifulSoup(r.content, 'html.parser')
    # for row in soup.find_all('div'):
    #     print(row.get_text())

    table = soup.find_all('div',class_="row")[1:2][0]
    rows = table.find_all('div',class_="row")[1:]
    print(len(rows))

    for row_ind in range(3,len(rows),3):#len(rows),3):
       # try :
        if row_ind + 2 < len(rows) :
            person_dict = {}
            names_row = rows[row_ind].get_text().strip().split('\n')
            person_dict['Place Overall'] = names_row[0]
            person_dict['Place Gender'] = names_row[1]
            person_dict['Place Division'] = names_row[2]
            person_dict['full_name'] = names_row[-1]
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip().split('(')[0]
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
                if len(person_dict['full_name'].split('(')) > 1 :
                    person_dict['country'] = person_dict['full_name'].split('(')[1].strip()[:-1]
                else :
                    person_dict['country'] = None
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

            person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = rows[row_ind + 1].get_text().strip().split('\n')[1][3:]
            times = rows[row_ind + 2].get_text().strip().split('\n')
            person_dict['half_marathon_split'] = times[0][4:]
            person_dict['full_split'] = times[1][10:]
            person_dict['finish_gun_time'] = times[2][10:]
            #print(row_ind,rows[row_ind].get_text())
            person_dicts.append(person_dict)
#         except :
#             #rint(rows[row_ind])
    
#             #print(rows[row_ind])
#person_dicts
df_boston_2021_1 = pd.DataFrame.from_dict(person_dicts)
df_boston_2021_1

dicts length 0
79
dicts length 25
79
dicts length 50
79
dicts length 75
79
dicts length 100
79
dicts length 125
79
dicts length 150
79
dicts length 175
79
dicts length 200
79
dicts length 225
79
dicts length 250
79
dicts length 275
79
dicts length 300
79
dicts length 325
79
dicts length 350
79
dicts length 375
79
dicts length 400
79
dicts length 425
79
dicts length 450
79
dicts length 475
79
dicts length 500
79
dicts length 525
79
dicts length 550
79
dicts length 575
79
dicts length 600
79
dicts length 625
79
dicts length 650
79
dicts length 675
79
dicts length 700
79
dicts length 725
79
dicts length 750
79
dicts length 775
79
dicts length 800
79
dicts length 825
79
dicts length 850
79
dicts length 875
79
dicts length 900
79
dicts length 925
79
dicts length 950
79
dicts length 975
79
dicts length 1000
79
dicts length 1025
79
dicts length 1050
79
dicts length 1075
79
dicts length 1100
79
dicts length 1125
79
dicts length 1150
79
dicts length 1175
79
dicts length 1200
79
dicts length 1225
79
dicts length 1250
79
dicts length 1275
79
dicts length 1300
79
dicts length 1325
79
dicts length 1350
79
dicts length 1375
79
dicts length 1400
79
dicts length 1425
79
dicts length 1450
79
dicts length 1475
79
dicts length 1500
79
dicts length 1525
79
dicts length 1550
79
dicts length 1575
79
dicts length 1600
79
dicts length 1625
79
dicts length 1650
79
dicts length 1675
79
dicts length 1700
79
dicts length 1725
79
dicts length 1750
79
dicts length 1775
79
dicts length 1800
79
dicts length 1825
79
dicts length 1850
79
dicts length 1875
79
dicts length 1900
79
dicts length 1925
79
dicts length 1950
79
dicts length 1975
79
dicts length 2000
79
dicts length 2025
79
dicts length 2050
79
dicts length 2075
79
dicts length 2100
79
dicts length 2125
79
dicts length 2150
79
dicts length 2175
79
dicts length 2200
79
dicts length 2225
79
dicts length 2250
79
dicts length 2275
79
dicts length 2300
79
dicts length 2325
79
dicts length 2350
79
dicts length 2375
79
dicts length 2400
79
dicts length 2425
79
dicts length 2450
79
dicts length 2475
79
dicts length 2500
79
dicts length 2525
79
dicts length 2550
79
dicts length 2575
79
dicts length 2600
79
dicts length 2625
79
dicts length 2650
79
dicts length 2675
79
dicts length 2700
79
dicts length 2725
79
dicts length 2750
79
dicts length 2775
79
dicts length 2800
79
dicts length 2825
79
dicts length 2850
79
dicts length 2875
79
dicts length 2900
79
dicts length 2925
79
dicts length 2950
79
dicts length 2975
79
dicts length 3000
79
dicts length 3025
79
dicts length 3050
79
dicts length 3075
79
dicts length 3100
79
dicts length 3125
79
dicts length 3150
79
dicts length 3175
79
dicts length 3200
79
dicts length 3225
79
dicts length 3250
79
dicts length 3275
79
dicts length 3300
79
dicts length 3325
79
dicts length 3350
79
dicts length 3375
79
dicts length 3400
79
dicts length 3425
79
dicts length 3450
79
dicts length 3475
79
dicts length 3500
79
dicts length 3525
79
dicts length 3550
79
dicts length 3575
79
dicts length 3600
79
dicts length 3625
79
dicts length 3650
79
dicts length 3675
79
dicts length 3700
79
dicts length 3725
79
dicts length 3750
79
dicts length 3775
79
dicts length 3800
79
dicts length 3825
79
dicts length 3850
79
dicts length 3875
79
dicts length 3900
79
dicts length 3925
79
dicts length 3950
79
dicts length 3975
79
dicts length 4000
79
dicts length 4025
79
dicts length 4050
79
dicts length 4075
79
dicts length 4100
79
dicts length 4125
79
dicts length 4150
79
dicts length 4175
79
dicts length 4200
79
dicts length 4225
79
dicts length 4250
79
dicts length 4275
79
dicts length 4300
79
dicts length 4325
79
dicts length 4350
79
dicts length 4375
79
dicts length 4400
79
dicts length 4425
79
dicts length 4450
79
dicts length 4475
79
dicts length 4500
79
dicts length 4525
79
dicts length 4550
79
dicts length 4575
79
dicts length 4600
79
dicts length 4625
79
dicts length 4650
79
dicts length 4675
79
dicts length 4700
79
dicts length 4725
79
dicts length 4750
79
dicts length 4775
79
dicts length 4800
79
dicts length 4825
79
dicts length 4850
79
dicts length 4875
79
dicts length 4900
79
dicts length 4925
79
dicts length 4950
79
dicts length 4975
79
dicts length 5000
79
dicts length 5025
79
dicts length 5050
79
dicts length 5075
79
dicts length 5100
79
dicts length 5125
79
dicts length 5150
79
dicts length 5175
79
dicts length 5200
79
dicts length 5225
79
dicts length 5250
79
dicts length 5275
79
dicts length 5300
79
dicts length 5325
79
dicts length 5350
79
dicts length 5375
79
dicts length 5400
79
dicts length 5425
79
dicts length 5450
79
dicts length 5475
79
dicts length 5500
79
dicts length 5525
79
dicts length 5550
79
dicts length 5575
79
dicts length 5600
79
dicts length 5625
79
dicts length 5650
79
dicts length 5675
79
dicts length 5700
79
dicts length 5725
79
dicts length 5750
79
dicts length 5775
79
dicts length 5800
79
dicts length 5825
79
dicts length 5850
79
dicts length 5875
79
dicts length 5900
79
dicts length 5925
79
dicts length 5950
79
dicts length 5975
79
dicts length 6000
79
dicts length 6025
79
dicts length 6050
79
dicts length 6075
79
dicts length 6100
79
dicts length 6125
79
dicts length 6150
79
dicts length 6175
79
dicts length 6200
79
dicts length 6225
79
dicts length 6250
79
dicts length 6275
79
dicts length 6300
79
dicts length 6325
79
dicts length 6350
79
dicts length 6375
79
dicts length 6400
79
dicts length 6425
79
dicts length 6450
79
dicts length 6475
79
dicts length 6500
79
dicts length 6525
79
dicts length 6550
79
dicts length 6575
79
dicts length 6600
79
dicts length 6625
79
dicts length 6650
79
dicts length 6675
79
dicts length 6700
79
dicts length 6725
79
dicts length 6750
79
dicts length 6775
79
dicts length 6800
79
dicts length 6825
79
dicts length 6850
79
dicts length 6875
79
dicts length 6900
79
dicts length 6925
79
dicts length 6950
79
dicts length 6975
79
dicts length 7000
79
dicts length 7025
79
dicts length 7050
79
dicts length 7075
79
dicts length 7100
79
dicts length 7125
79
dicts length 7150
79
dicts length 7175
79
dicts length 7200
79
dicts length 7225
79
dicts length 7250
79
dicts length 7275
79
dicts length 7300
79
dicts length 7325
79
dicts length 7350
79
dicts length 7375
79
dicts length 7400
79
dicts length 7425
79
dicts length 7450
79
dicts length 7475
79
dicts length 7500
79
dicts length 7525
79
dicts length 7550
79
dicts length 7575
79
dicts length 7600
79
dicts length 7625
79
dicts length 7650
79
dicts length 7675
79
dicts length 7700
79
dicts length 7725
79
dicts length 7750
79
dicts length 7775
79
dicts length 7800
79
dicts length 7825
79
dicts length 7850
79
dicts length 7875
79
dicts length 7900
79
dicts length 7925
55
dicts length 7942
4
dicts length 7942
4
dicts length 7942
4

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,country,team,bib_number,half_marathon_split,full_split,finish_gun_time
0,1,1,1,"Kipruto, Benson (KEN)",Benson,Kipruto,KEN,–,4,01:06:22,02:09:51,02:09:51
1,2,2,2,"Berhanu, Lemi (ETH)",Lemi,Berhanu,ETH,–,3,01:06:23,02:10:37,02:10:37
2,3,3,3,"Yimer, Jemal (ETH)",Jemal,Yimer,ETH,–,21,01:06:21,02:10:38,02:10:38
3,4,4,4,"Ayana, Tsedat (ETH)",Tsedat,Ayana,ETH,–,12,01:06:22,02:10:47,02:10:47
4,5,5,5,"Barsoton, Leonard (KEN)",Leonard,Barsoton,KEN,–,22,01:06:22,02:11:11,02:11:11
...,...,...,...,...,...,...,...,...,...,...,...,...
7937,15373,7938,729,"Wan, Yongbing (USA)",Yongbing,Wan,USA,–,11992,03:34:16,07:04:13,07:16:14
7938,15374,7939,2232,"Roundtree, Ernest (USA)",Ernest,Roundtree,USA,–,3720,03:18:44,07:04:32,07:04:59
7939,15380,7940,145,"Robinson, Harold (USA)",Harold,Robinson,USA,–,3546,03:35:08,07:22:59,07:31:36
7940,15382,7941,2233,"Quinn, Adam (USA)",Adam,Quinn,USA,–,3698,02:53:29,07:24:34,07:24:56
7941,15384,7942,1116,"Pierre, John (USA)",John,Pierre,USA,–,3714,03:38:05,07:51:35,07:51:47

In [119]:
df_boston_2021_1.to_csv('boston_marathon_results_2021_mens.csv')

In [66]:
url = """
http://registration.baa.org/cfm_Archive/iframe_ArchiveSearch.cfm?mode=\
results&criteria=&StoredProcParamsOn=yes&&VarRaceYearLowID=2018&Var\
RaceYearHighID=2019&VarAgeLowID=0&VarAgeHighID=0&VarGenderID=0&VarBibNumber=\
&VarLastName=&VarFirstName=&VarStateID=0&VarCountryOfResidenceID=0&VarCity=&\
VarZip=&VarTimeLowHr=&VarTimeLowMin=&VarTimeLowSec=00&VarTimeHighHr=&VarTimeHighMin=\
&VarTimeHighSec=59&VarSortOrder=ByName&VarAddInactiveYears=0&records=25\
&headerexists=Yes&bordersize=0&bordercolor=%23ffffff&rowcolorone=%23FFCC33\
&rowcolortwo=%23FFCC33&headercolor=%23ffffff&headerfontface=Verdana%2CArial\
%2CHelvetica%2Csans%2Dserif&headerfontcolor=%23004080&headerfontsize=12px&fontface=Verdana\
%2CArial%2CHelvetica%2Csans%2Dserif&fontcolor=%23000099&fontsize=10px&linkfield=&linkurl=&\
linkparams=&queryname=SearchResults&tablefields=RaceYear%2CFullBibNumber%2CFormattedSortName%2CAgeOnRaceDay\
%2CGenderCode%2CCity%2CStateAbbrev%2CCountryOfResAbbrev%2CReportingSegment


"""
url = 'http://registration.baa.org/cfm_Archive/iframe_ArchiveSearch.cfm'
person_dicts = []
start_num = 1

while start_num < 26657 : 
    print(start_num,len(person_dicts))

    year = 2019
    gender = 0
    data = {'start': start_num, 'next': 'Next 25 Records'}
    params = {'mode': 'results', 'criteria': '',
              'StoredProcParamsOn': 'yes', '': '',
              'VarRaceYearLowID': year, 'VarRaceYearHighID': 0,
              'VarAgeLowID': 0, 'VarAgeHighID': 0, 'VarGenderID': gender,
              'VarBibNumber': '', 'VarLastName': '',
              'VarFirstName': '', 'VarStateID': 0,
              'VarCountryOfResidenceID': 0, 'VarCity': '', 'VarZip': '',
              'VarTimeLowHr': '', 'VarTimeLowMin': '',
              'VarTimeLowSec': '00', 'VarTimeHighHr': '',
              'VarTimeHighMin': '', 'VarTimeHighSec': '59',
              'VarSortOrder': 'ByName', 'VarAddInactiveYears': 0,
              'records': 25, 'headerexists': 'Yes',
              'bordersize': 0, 'bordercolor': '#ffffff',
              'rowcolorone': '#FFCC33', 'rowcolortwo': '#FFCC33',
              'headercolor': '#ffffff',
              'headerfontface': 'Verdana,Arial,Helvetica,sans-serif',
              'headerfontcolor': '#004080', 'headerfontsize': '12px',
              'fontface': 'Verdana,Arial,Helvetica,sans-serif',
              'fontcolor': '#000099', 'fontsize': '10px', 'linkfield': '',
              'linkurl': '', 'linkparams': '',
              'queryname': 'SearchResults',
              'tablefields': 'RaceYear,FullBibNumber,FormattedSortName,AgeOnRaceDay,GenderCode,City,StateAbbrev,CountryOfResAbbrev,ReportingSegment'}
    r = requests.post(url, data=data, params=params)
    soup = BeautifulSoup(r.content, 'html.parser')


    num_cols = 15
    first = 0
    table = soup.find_all('table',class_="tablegrid_table")[0]
    #print(table)
    for x in range(25) :
        row = table.find_all('td')[first:first+num_cols]
        person_dict = {}
        person_dict['Year'] = row[0].get_text().strip()
        person_dict['Place Overall'] = row[10].get_text().strip().split('/')[0].strip()
        person_dict['Place Gender'] = row[11].get_text().strip().split('/')[0].strip()
        person_dict['Place Division'] = row[12].get_text().strip().split('/')[0].strip()
        person_dict['full_name'] = row[2].get_text().strip()
        if len(person_dict['full_name'].split(',')) > 1 :
            person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
            person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
        else :
            person_dict['first_name'] = None
            person_dict['last_name'] = None

    #     person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
        person_dict['bib_number'] = row[1].get_text().strip()
        person_dict['Age'] = row[3].get_text().strip()
        person_dict['Gender'] = row[4].get_text().strip()
        person_dict['City'] = row[5].get_text().strip()
        person_dict['State'] = row[6].get_text().strip()
        person_dict['Country'] = row[7].get_text().strip()
        #times = rows[row_ind + 2].get_text().strip().split('\n')
    #     person_dict['half_marathon_split'] = times[0][4:]
        person_dict['Official Time'] = row[13].get_text().strip()
        person_dict['Net Time'] = row[14].get_text().strip()
        person_dicts.append(person_dict)  
        first+= num_cols
    start_num +=25
    
    
df_boston_2019 = pd.DataFrame.from_dict(person_dicts)
df_boston_2019

1 0
26 25
51 50
76 75
101 100
126 125
151 150
176 175
201 200
226 225
251 250
276 275
301 300
326 325
351 350
376 375
401 400
426 425
451 450
476 475
501 500
526 525
551 550
576 575
601 600
626 625
651 650
676 675
701 700
726 725
751 750
776 775
801 800
826 825
851 850
876 875
901 900
926 925
951 950
976 975
1001 1000
1026 1025
1051 1050
1076 1075
1101 1100
1126 1125
1151 1150
1176 1175
1201 1200
1226 1225
1251 1250
1276 1275
1301 1300
1326 1325
1351 1350
1376 1375
1401 1400
1426 1425
1451 1450
1476 1475
1501 1500
1526 1525
1551 1550
1576 1575
1601 1600
1626 1625
1651 1650
1676 1675
1701 1700
1726 1725
1751 1750
1776 1775
1801 1800
1826 1825
1851 1850
1876 1875
1901 1900
1926 1925
1951 1950
1976 1975
2001 2000
2026 2025
2051 2050
2076 2075
2101 2100
2126 2125
2151 2150
2176 2175
2201 2200
2226 2225
2251 2250
2276 2275
2301 2300
2326 2325
2351 2350
2376 2375
2401 2400
2426 2425
2451 2450
2476 2475
2501 2500
2526 2525
2551 2550
2576 2575
2601 2600
2626 2625
2651 2650
2676 2675
2701 2700
2726 2725
2751 2750
2776 2775
2801 2800
2826 2825
2851 2850
2876 2875
2901 2900
2926 2925
2951 2950
2976 2975
3001 3000
3026 3025
3051 3050
3076 3075
3101 3100
3126 3125
3151 3150
3176 3175
3201 3200
3226 3225
3251 3250
3276 3275
3301 3300
3326 3325
3351 3350
3376 3375
3401 3400
3426 3425
3451 3450
3476 3475
3501 3500
3526 3525
3551 3550
3576 3575
3601 3600
3626 3625
3651 3650
3676 3675
3701 3700
3726 3725
3751 3750
3776 3775
3801 3800
3826 3825
3851 3850
3876 3875
3901 3900
3926 3925
3951 3950
3976 3975
4001 4000
4026 4025
4051 4050
4076 4075
4101 4100
4126 4125
4151 4150
4176 4175
4201 4200
4226 4225
4251 4250
4276 4275
4301 4300
4326 4325
4351 4350
4376 4375
4401 4400
4426 4425
4451 4450
4476 4475
4501 4500
4526 4525
4551 4550
4576 4575
4601 4600
4626 4625
4651 4650
4676 4675
4701 4700
4726 4725
4751 4750
4776 4775
4801 4800
4826 4825
4851 4850
4876 4875
4901 4900
4926 4925
4951 4950
4976 4975
5001 5000
5026 5025
5051 5050
5076 5075
5101 5100
5126 5125
5151 5150
5176 5175
5201 5200
5226 5225
5251 5250
5276 5275
5301 5300
5326 5325
5351 5350
5376 5375
5401 5400
5426 5425
5451 5450
5476 5475
5501 5500
5526 5525
5551 5550
5576 5575
5601 5600
5626 5625
5651 5650
5676 5675
5701 5700
5726 5725
5751 5750
5776 5775
5801 5800
5826 5825
5851 5850
5876 5875
5901 5900
5926 5925
5951 5950
5976 5975
6001 6000
6026 6025
6051 6050
6076 6075
6101 6100
6126 6125
6151 6150
6176 6175
6201 6200
6226 6225
6251 6250
6276 6275
6301 6300
6326 6325
6351 6350
6376 6375
6401 6400
6426 6425
6451 6450
6476 6475
6501 6500
6526 6525
6551 6550
6576 6575
6601 6600
6626 6625
6651 6650
6676 6675
6701 6700
6726 6725
6751 6750
6776 6775
6801 6800
6826 6825
6851 6850
6876 6875
6901 6900
6926 6925
6951 6950
6976 6975
7001 7000
7026 7025
7051 7050
7076 7075
7101 7100
7126 7125
7151 7150
7176 7175
7201 7200
7226 7225
7251 7250
7276 7275
7301 7300
7326 7325
7351 7350
7376 7375
7401 7400
7426 7425
7451 7450
7476 7475
7501 7500
7526 7525
7551 7550
7576 7575
7601 7600
7626 7625
7651 7650
7676 7675
7701 7700
7726 7725
7751 7750
7776 7775
7801 7800
7826 7825
7851 7850
7876 7875
7901 7900
7926 7925
7951 7950
7976 7975
8001 8000
8026 8025
8051 8050
8076 8075
8101 8100
8126 8125
8151 8150
8176 8175
8201 8200
8226 8225
8251 8250
8276 8275
8301 8300
8326 8325
8351 8350
8376 8375
8401 8400
8426 8425
8451 8450
8476 8475
8501 8500
8526 8525
8551 8550
8576 8575
8601 8600
8626 8625
8651 8650
8676 8675
8701 8700
8726 8725
8751 8750
8776 8775
8801 8800
8826 8825
8851 8850
8876 8875
8901 8900
8926 8925
8951 8950
8976 8975
9001 9000
9026 9025
9051 9050
9076 9075
9101 9100
9126 9125
9151 9150
9176 9175
9201 9200
9226 9225
9251 9250
9276 9275
9301 9300
9326 9325
9351 9350
9376 9375
9401 9400
9426 9425
9451 9450
9476 9475
9501 9500
9526 9525
9551 9550
9576 9575
9601 9600
9626 9625
9651 9650
9676 9675
9701 9700
9726 9725
9751 9750
9776 9775
9801 9800
9826 9825
9851 9850
9876 9875
9901 9900
9926 9925
9951 9950
9976 9975
10001 10000
10026 10025
10051 10050
10076 10075
10101 10100
10126 10125
10151 10150
10176 10175
10201 10200
10226 10225
10251 10250
10276 10275
10301 10300
10326 10325
10351 10350
10376 10375
10401 10400
10426 10425
10451 10450
10476 10475
10501 10500
10526 10525
10551 10550
10576 10575
10601 10600
10626 10625
10651 10650
10676 10675
10701 10700
10726 10725
10751 10750
10776 10775
10801 10800
10826 10825
10851 10850
10876 10875
10901 10900
10926 10925
10951 10950
10976 10975
11001 11000
11026 11025
11051 11050
11076 11075
11101 11100
11126 11125
11151 11150
11176 11175
11201 11200
11226 11225
11251 11250
11276 11275
11301 11300
11326 11325
11351 11350
11376 11375
11401 11400
11426 11425
11451 11450
11476 11475
11501 11500
11526 11525
11551 11550
11576 11575
11601 11600
11626 11625
11651 11650
11676 11675
11701 11700
11726 11725
11751 11750
11776 11775
11801 11800
11826 11825
11851 11850
11876 11875
11901 11900
11926 11925
11951 11950
11976 11975
12001 12000
12026 12025
12051 12050
12076 12075
12101 12100
12126 12125
12151 12150
12176 12175
12201 12200
12226 12225
12251 12250
12276 12275
12301 12300
12326 12325
12351 12350
12376 12375
12401 12400
12426 12425
12451 12450
12476 12475
12501 12500
12526 12525
12551 12550
12576 12575
12601 12600
12626 12625
12651 12650
12676 12675
12701 12700
12726 12725
12751 12750
12776 12775
12801 12800
12826 12825
12851 12850
12876 12875
12901 12900
12926 12925
12951 12950
12976 12975
13001 13000
13026 13025
13051 13050
13076 13075
13101 13100
13126 13125
13151 13150
13176 13175
13201 13200
13226 13225
13251 13250
13276 13275
13301 13300
13326 13325
13351 13350
13376 13375
13401 13400
13426 13425
13451 13450
13476 13475
13501 13500
13526 13525
13551 13550
13576 13575
13601 13600
13626 13625
13651 13650
13676 13675
13701 13700
13726 13725
13751 13750
13776 13775
13801 13800
13826 13825
13851 13850
13876 13875
13901 13900
13926 13925
13951 13950
13976 13975
14001 14000
14026 14025
14051 14050
14076 14075
14101 14100
14126 14125
14151 14150
14176 14175
14201 14200
14226 14225
14251 14250
14276 14275
14301 14300
14326 14325
14351 14350
14376 14375
14401 14400
14426 14425
14451 14450
14476 14475
14501 14500
14526 14525
14551 14550
14576 14575
14601 14600
14626 14625
14651 14650
14676 14675
14701 14700
14726 14725
14751 14750
14776 14775
14801 14800
14826 14825
14851 14850
14876 14875
14901 14900
14926 14925
14951 14950
14976 14975
15001 15000
15026 15025
15051 15050
15076 15075
15101 15100
15126 15125
15151 15150
15176 15175
15201 15200
15226 15225
15251 15250
15276 15275
15301 15300
15326 15325
15351 15350
15376 15375
15401 15400
15426 15425
15451 15450
15476 15475
15501 15500
15526 15525
15551 15550
15576 15575
15601 15600
15626 15625
15651 15650
15676 15675
15701 15700
15726 15725
15751 15750
15776 15775
15801 15800
15826 15825
15851 15850
15876 15875
15901 15900
15926 15925
15951 15950
15976 15975
16001 16000
16026 16025
16051 16050
16076 16075
16101 16100
16126 16125
16151 16150
16176 16175
16201 16200
16226 16225
16251 16250
16276 16275
16301 16300
16326 16325
16351 16350
16376 16375
16401 16400
16426 16425
16451 16450
16476 16475
16501 16500
16526 16525
16551 16550
16576 16575
16601 16600
16626 16625
16651 16650
16676 16675
16701 16700
16726 16725
16751 16750
16776 16775
16801 16800
16826 16825
16851 16850
16876 16875
16901 16900
16926 16925
16951 16950
16976 16975
17001 17000
17026 17025
17051 17050
17076 17075
17101 17100
17126 17125
17151 17150
17176 17175
17201 17200
17226 17225
17251 17250
17276 17275
17301 17300
17326 17325
17351 17350
17376 17375
17401 17400
17426 17425
17451 17450
17476 17475
17501 17500
17526 17525
17551 17550
17576 17575
17601 17600
17626 17625
17651 17650
17676 17675
17701 17700
17726 17725
17751 17750
17776 17775
17801 17800
17826 17825
17851 17850
17876 17875
17901 17900
17926 17925
17951 17950
17976 17975
18001 18000
18026 18025
18051 18050
18076 18075
18101 18100
18126 18125
18151 18150
18176 18175
18201 18200
18226 18225
18251 18250
18276 18275
18301 18300
18326 18325
18351 18350
18376 18375
18401 18400
18426 18425
18451 18450
18476 18475
18501 18500
18526 18525
18551 18550
18576 18575
18601 18600
18626 18625
18651 18650
18676 18675
18701 18700
18726 18725
18751 18750
18776 18775
18801 18800
18826 18825
18851 18850
18876 18875
18901 18900

18926 18925
18951 18950
18976 18975
19001 19000
19026 19025
19051 19050
19076 19075
19101 19100
19126 19125
19151 19150
19176 19175
19201 19200
19226 19225
19251 19250
19276 19275
19301 19300
19326 19325
19351 19350
19376 19375
19401 19400
19426 19425
19451 19450
19476 19475
19501 19500
19526 19525
19551 19550
19576 19575
19601 19600
19626 19625
19651 19650
19676 19675
19701 19700
19726 19725
19751 19750
19776 19775
19801 19800
19826 19825
19851 19850
19876 19875
19901 19900
19926 19925
19951 19950
19976 19975
20001 20000
20026 20025
20051 20050
20076 20075
20101 20100
20126 20125
20151 20150
20176 20175
20201 20200
20226 20225
20251 20250
20276 20275
20301 20300
20326 20325
20351 20350
20376 20375
20401 20400
20426 20425
20451 20450
20476 20475
20501 20500
20526 20525
20551 20550
20576 20575
20601 20600
20626 20625
20651 20650
20676 20675
20701 20700
20726 20725
20751 20750
20776 20775
20801 20800
20826 20825
20851 20850
20876 20875
20901 20900
20926 20925
20951 20950
20976 20975
21001 21000
21026 21025
21051 21050
21076 21075
21101 21100
21126 21125
21151 21150
21176 21175
21201 21200
21226 21225
21251 21250
21276 21275
21301 21300
21326 21325
21351 21350
21376 21375
21401 21400
21426 21425
21451 21450
21476 21475
21501 21500
21526 21525
21551 21550
21576 21575
21601 21600
21626 21625
21651 21650
21676 21675
21701 21700
21726 21725
21751 21750
21776 21775
21801 21800
21826 21825
21851 21850
21876 21875
21901 21900
21926 21925
21951 21950
21976 21975
22001 22000
22026 22025
22051 22050
22076 22075
22101 22100
22126 22125
22151 22150
22176 22175
22201 22200
22226 22225
22251 22250
22276 22275
22301 22300
22326 22325
22351 22350
22376 22375
22401 22400
22426 22425
22451 22450
22476 22475
22501 22500
22526 22525
22551 22550
22576 22575
22601 22600
22626 22625
22651 22650
22676 22675
22701 22700
22726 22725
22751 22750
22776 22775
22801 22800
22826 22825
22851 22850
22876 22875
22901 22900
22926 22925
22951 22950
22976 22975
23001 23000
23026 23025
23051 23050
23076 23075
23101 23100
23126 23125
23151 23150
23176 23175
23201 23200
23226 23225
23251 23250
23276 23275
23301 23300
23326 23325
23351 23350
23376 23375
23401 23400
23426 23425
23451 23450
23476 23475
23501 23500
23526 23525
23551 23550
23576 23575
23601 23600
23626 23625
23651 23650
23676 23675
23701 23700
23726 23725
23751 23750
23776 23775
23801 23800
23826 23825
23851 23850
23876 23875
23901 23900
23926 23925
23951 23950
23976 23975
24001 24000
24026 24025
24051 24050
24076 24075
24101 24100
24126 24125
24151 24150
24176 24175
24201 24200
24226 24225
24251 24250
24276 24275
24301 24300
24326 24325
24351 24350
24376 24375
24401 24400
24426 24425
24451 24450
24476 24475
24501 24500
24526 24525
24551 24550
24576 24575
24601 24600
24626 24625
24651 24650
24676 24675
24701 24700
24726 24725
24751 24750
24776 24775
24801 24800
24826 24825
24851 24850
24876 24875
24901 24900
24926 24925
24951 24950
24976 24975
25001 25000
25026 25025
25051 25050
25076 25075
25101 25100
25126 25125
25151 25150
25176 25175
25201 25200
25226 25225
25251 25250
25276 25275
25301 25300
25326 25325
25351 25350
25376 25375
25401 25400
25426 25425
25451 25450
25476 25475
25501 25500
25526 25525
25551 25550
25576 25575
25601 25600
25626 25625
25651 25650
25676 25675
25701 25700
25726 25725
25751 25750
25776 25775
25801 25800
25826 25825
25851 25850
25876 25875
25901 25900
25926 25925
25951 25950
25976 25975
26001 26000
26026 26025
26051 26050
26076 26075
26101 26100
26126 26125
26151 26150
26176 26175
26201 26200
26226 26225
26251 26250
26276 26275
26301 26300
26326 26325
26351 26350
26376 26375
26401 26400
26426 26425
26451 26450
26476 26475
26501 26500
26526 26525
26551 26550
26576 26575
26601 26600
26626 26625
26651 26650

,Year,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,bib_number,Age,Gender,City,State,Country,Official Time,Net Time
0,2019,17778,10733,4132,"Aaflaq, Peter",Peter,Aaflaq,2245,19,M,Carbondale,IL,USA,4:06:23,4:05:22
1,2019,17139,10486,1355,"Aaldijk, Aart",Aart,Aaldijk,28431,51,M,Raamsdonksveer,,NED,4:29:06,4:01:42
2,2019,12140,3752,2553,"Aames, Susie",Susie,Aames,14710,29,F,Alhambra,CA,USA,3:45:33,3:41:06
3,2019,296,275,237,"Aarnes, Hans Chr.",Hans Chr.,Aarnes,411,34,M,Nittedal,,NOR,2:38:31,2:38:27
4,2019,5050,4445,804,"Aaronson, Matt",Matt,Aaronson,3781,43,M,Chicago,IL,USA,3:15:23,3:13:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26670,2019,6445,5432,968,"Zilm, Josh",Josh,Zilm,7670,41,M,Neenah,WI,USA,3:23:46,3:19:32
26671,2019,6216,5267,3039,"Ziluca, Daniel",Daniel,Ziluca,1946,34,M,New York,NY,USA,3:19:05,3:18:35
26672,2019,173,160,141,"Zimak, Trevor",Trevor,Zimak,57,35,M,Thunder Bay,ON,CAN,2:33:59,2:33:59
26673,2019,7772,6253,546,"Zimerman, Dan",Dan,Zimerman,10144,53,M,Montclair,NJ,USA,3:26:52,3:24:55
26674,2019,17871,7110,3842,"Zimmer, Brandy",Brandy,Zimmer,15054,37,F,Spring,TX,USA,4:11:05,4:05:52

In [71]:
url = 'http://registration.baa.org/cfm_Archive/iframe_ArchiveSearch.cfm'
person_dicts = []
start_num = 26674

while start_num < 26761 : 
    print(start_num,len(person_dicts))

    year = 2019
    gender = 0
    data = {'start': start_num, 'next': 'Next 25 Records'}
    params = {'mode': 'results', 'criteria': '',
              'StoredProcParamsOn': 'yes', '': '',
              'VarRaceYearLowID': year, 'VarRaceYearHighID': 0,
              'VarAgeLowID': 0, 'VarAgeHighID': 0, 'VarGenderID': gender,
              'VarBibNumber': '', 'VarLastName': '',
              'VarFirstName': '', 'VarStateID': 0,
              'VarCountryOfResidenceID': 0, 'VarCity': '', 'VarZip': '',
              'VarTimeLowHr': '', 'VarTimeLowMin': '',
              'VarTimeLowSec': '00', 'VarTimeHighHr': '',
              'VarTimeHighMin': '', 'VarTimeHighSec': '59',
              'VarSortOrder': 'ByName', 'VarAddInactiveYears': 0,
              'records': 25, 'headerexists': 'Yes',
              'bordersize': 0, 'bordercolor': '#ffffff',
              'rowcolorone': '#FFCC33', 'rowcolortwo': '#FFCC33',
              'headercolor': '#ffffff',
              'headerfontface': 'Verdana,Arial,Helvetica,sans-serif',
              'headerfontcolor': '#004080', 'headerfontsize': '12px',
              'fontface': 'Verdana,Arial,Helvetica,sans-serif',
              'fontcolor': '#000099', 'fontsize': '10px', 'linkfield': '',
              'linkurl': '', 'linkparams': '',
              'queryname': 'SearchResults',
              'tablefields': 'RaceYear,FullBibNumber,FormattedSortName,AgeOnRaceDay,GenderCode,City,StateAbbrev,CountryOfResAbbrev,ReportingSegment'}
    r = requests.post(url, data=data, params=params)
    soup = BeautifulSoup(r.content, 'html.parser')


    num_cols = 15
    first = 0
    table = soup.find_all('table',class_="tablegrid_table")[0]
    #print(table)
    for x in range(25) :
        row = table.find_all('td')[first:first+num_cols]
        person_dict = {}
        if len(row) > 0 :
            person_dict['Year'] = row[0].get_text().strip()
            if len(row) > 9 :

                person_dict['Place Overall'] = row[10].get_text().strip().split('/')[0].strip()
                person_dict['Place Gender'] = row[11].get_text().strip().split('/')[0].strip()
                person_dict['Place Division'] = row[12].get_text().strip().split('/')[0].strip()
            else :
                person_dict['Place Overall'] = None
                person_dict['Place Gender'] = None
                person_dict['Place Division'] = None
            person_dict['full_name'] = row[2].get_text().strip()
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

        #     person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = row[1].get_text().strip()

            if len(row) > 3:
                person_dict['Age'] = row[3].get_text().strip()
                person_dict['Gender'] = row[4].get_text().strip()
                person_dict['City'] = row[5].get_text().strip()
                person_dict['State'] = row[6].get_text().strip()
                person_dict['Country'] = row[7].get_text().strip()
                #times = rows[row_ind + 2].get_text().strip().split('\n')
            #     person_dict['half_marathon_split'] = times[0][4:]
                person_dict['Official Time'] = row[13].get_text().strip()
                person_dict['Net Time'] = row[14].get_text().strip()
            else :
                person_dict['Age'] = None
                person_dict['Gender'] = None
                person_dict['City'] = None
                person_dict['State'] =None
                person_dict['Country'] = None
                #times = rows[row_ind + 2].get_text().strip().split('\n')
            #     person_dict['half_marathon_split'] = times[0][4:]
                person_dict['Official Time'] = None
                person_dict['Net Time'] = None
        person_dicts.append(person_dict)  
        first+= num_cols
    start_num +=25
    
df_boston_2019_1 = pd.DataFrame.from_dict(person_dicts)
df_boston_2019_1

26674 0
26699 25
26724 50
26749 75

,Year,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,bib_number,Age,Gender,City,State,Country,Official Time,Net Time
0,2019,7772,6253,546,"Zimerman, Dan",Dan,Zimerman,10144,53,M,Montclair,NJ,USA,3:26:52,3:24:55
1,2019,17871,7110,3842,"Zimmer, Brandy",Brandy,Zimmer,15054,37,F,Spring,TX,USA,4:11:05,4:05:52
2,2019,6731,5625,1012,"Zimmer, Mark",Mark,Zimmer,8513,44,M,St. Louis Park,MN,USA,3:20:52,3:20:40
3,2019,11469,8079,1462,"Zimmer, Scott",Scott,Zimmer,11195,46,M,Bentleyville,OH,USA,3:40:35,3:38:26
4,2019,3301,3042,24,"Zimmer, Kevin",Kevin,Zimmer,4136,56,M,Del Mar,CA,USA,3:06:56,3:04:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
df_boston_2019_1.dropna()[2:]

,Year,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,bib_number,Age,Gender,City,State,Country,Official Time,Net Time
2,2019,6731,5625,1012,"Zimmer, Mark",Mark,Zimmer,8513,44,M,St. Louis Park,MN,USA,3:20:52,3:20:40
3,2019,11469,8079,1462,"Zimmer, Scott",Scott,Zimmer,11195,46,M,Bentleyville,OH,USA,3:40:35,3:38:26
4,2019,3301,3042,24,"Zimmer, Kevin",Kevin,Zimmer,4136,56,M,Del Mar,CA,USA,3:06:56,3:04:15
5,2019,12151,8393,3715,"Zimmer, Nathan",Nathan,Zimmer,5815,37,M,Lithia,FL,USA,3:43:32,3:41:09
6,2019,16782,6430,215,"Zimmerman, Angela",Angela,Zimmerman,23585,57,F,Lake Oswego,OR,USA,4:05:17,3:59:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2019,4971,592,499,"Zwickert, Kristy",Kristy,Zwickert,14554,36,F,Jerrabomberra,,AUS,3:16:45,3:13:11
84,2019,10777,7770,874,"Zwiller, Stéphane",Stéphane,Zwiller,10230,52,M,Fesches Le Chatel,,FRA,3:37:26,3:35:55
85,2019,9057,6926,75,"Zyborowicz, Henry",Henry,Zyborowicz,16505,62,M,Philadelphia,PA,USA,3:29:38,3:29:19
86,2019,3,3,3,"Zybowski, Krys",Krys,Zybowski,H7,43,M,Avon,CT,USA,1:13:36,1:13:36
87,2019,19510,11441,1141,"Zylka, Edward",Edward,Zylka,19326,59,M,S Burlington,VT,USA,4:22:52,4:15:55

In [76]:
df_boston_2019_all = pd.concat([df_boston_2019,df_boston_2019_1.dropna()[2:]])
df_boston_2019_all

,Year,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,bib_number,Age,Gender,City,State,Country,Official Time,Net Time
0,2019,17778,10733,4132,"Aaflaq, Peter",Peter,Aaflaq,2245,19,M,Carbondale,IL,USA,4:06:23,4:05:22
1,2019,17139,10486,1355,"Aaldijk, Aart",Aart,Aaldijk,28431,51,M,Raamsdonksveer,,NED,4:29:06,4:01:42
2,2019,12140,3752,2553,"Aames, Susie",Susie,Aames,14710,29,F,Alhambra,CA,USA,3:45:33,3:41:06
3,2019,296,275,237,"Aarnes, Hans Chr.",Hans Chr.,Aarnes,411,34,M,Nittedal,,NOR,2:38:31,2:38:27
4,2019,5050,4445,804,"Aaronson, Matt",Matt,Aaronson,3781,43,M,Chicago,IL,USA,3:15:23,3:13:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2019,4971,592,499,"Zwickert, Kristy",Kristy,Zwickert,14554,36,F,Jerrabomberra,,AUS,3:16:45,3:13:11
84,2019,10777,7770,874,"Zwiller, Stéphane",Stéphane,Zwiller,10230,52,M,Fesches Le Chatel,,FRA,3:37:26,3:35:55
85,2019,9057,6926,75,"Zyborowicz, Henry",Henry,Zyborowicz,16505,62,M,Philadelphia,PA,USA,3:29:38,3:29:19
86,2019,3,3,3,"Zybowski, Krys",Krys,Zybowski,H7,43,M,Avon,CT,USA,1:13:36,1:13:36
87,2019,19510,11441,1141,"Zylka, Edward",Edward,Zylka,19326,59,M,S Burlington,VT,USA,4:22:52,4:15:55

In [77]:
df_boston_2019_all.to_csv('boston_2019.csv')

In [73]:
26675 + 88

26763

In [78]:
import scrape_boston

In [79]:
scrape_boston.scrape(2018, 25908)

2018 0 25908

IndexError: list index out of range

In [80]:
url = 'http://registration.baa.org/cfm_Archive/iframe_ArchiveSearch.cfm'
person_dicts = []
start_num = 26674

while start_num < 26761 : 
    print(start_num,len(person_dicts))

    year = 2019
    gender = 0
    data = {'start': start_num, 'next': 'Next 25 Records'}
    params = {'mode': 'results', 'criteria': '',
              'StoredProcParamsOn': 'yes', '': '',
              'VarRaceYearLowID': year, 'VarRaceYearHighID': 0,
              'VarAgeLowID': 0, 'VarAgeHighID': 0, 'VarGenderID': gender,
              'VarBibNumber': '', 'VarLastName': '',
              'VarFirstName': '', 'VarStateID': 0,
              'VarCountryOfResidenceID': 0, 'VarCity': '', 'VarZip': '',
              'VarTimeLowHr': '', 'VarTimeLowMin': '',
              'VarTimeLowSec': '00', 'VarTimeHighHr': '',
              'VarTimeHighMin': '', 'VarTimeHighSec': '59',
              'VarSortOrder': 'ByName', 'VarAddInactiveYears': 0,
              'records': 25, 'headerexists': 'Yes',
              'bordersize': 0, 'bordercolor': '#ffffff',
              'rowcolorone': '#FFCC33', 'rowcolortwo': '#FFCC33',
              'headercolor': '#ffffff',
              'headerfontface': 'Verdana,Arial,Helvetica,sans-serif',
              'headerfontcolor': '#004080', 'headerfontsize': '12px',
              'fontface': 'Verdana,Arial,Helvetica,sans-serif',
              'fontcolor': '#000099', 'fontsize': '10px', 'linkfield': '',
              'linkurl': '', 'linkparams': '',
              'queryname': 'SearchResults',
              'tablefields': 'RaceYear,FullBibNumber,FormattedSortName,AgeOnRaceDay,GenderCode,City,StateAbbrev,CountryOfResAbbrev,ReportingSegment'}
    r = requests.post(url, data=data, params=params)
    soup = BeautifulSoup(r.content, 'html.parser')


    num_cols = 15
    first = 0
    table = soup.find_all('table',class_="tablegrid_table")[0]
    #print(table)
    for x in range(25) :
        row = table.find_all('td')[first:first+num_cols]
        person_dict = {}
        if len(row) > 0 :
            person_dict['Year'] = row[0].get_text().strip()
            if len(row) > 9 :

                person_dict['Place Overall'] = row[10].get_text().strip().split('/')[0].strip()
                person_dict['Place Gender'] = row[11].get_text().strip().split('/')[0].strip()
                person_dict['Place Division'] = row[12].get_text().strip().split('/')[0].strip()
            else :
                person_dict['Place Overall'] = None
                person_dict['Place Gender'] = None
                person_dict['Place Division'] = None
            person_dict['full_name'] = row[2].get_text().strip()
            if len(person_dict['full_name'].split(',')) > 1 :
                person_dict['first_name'] = person_dict['full_name'].split(',')[1].strip()
                person_dict['last_name'] = person_dict['full_name'].split(',')[0].strip()
            else :
                person_dict['first_name'] = None
                person_dict['last_name'] = None

        #     person_dict['team'] = rows[row_ind + 1].get_text().strip().split('\n')[0][4:]
            person_dict['bib_number'] = row[1].get_text().strip()

            if len(row) > 3:
                person_dict['Age'] = row[3].get_text().strip()
                person_dict['Gender'] = row[4].get_text().strip()
                person_dict['City'] = row[5].get_text().strip()
                person_dict['State'] = row[6].get_text().strip()
                person_dict['Country'] = row[7].get_text().strip()
                #times = rows[row_ind + 2].get_text().strip().split('\n')
            #     person_dict['half_marathon_split'] = times[0][4:]
                person_dict['Official Time'] = row[13].get_text().strip()
                person_dict['Net Time'] = row[14].get_text().strip()
            else :
                person_dict['Age'] = None
                person_dict['Gender'] = None
                person_dict['City'] = None
                person_dict['State'] =None
                person_dict['Country'] = None
                #times = rows[row_ind + 2].get_text().strip().split('\n')
            #     person_dict['half_marathon_split'] = times[0][4:]
                person_dict['Official Time'] = None
                person_dict['Net Time'] = None
        person_dicts.append(person_dict)  
        first+= num_cols
    start_num +=25
    
df_boston_2019_1 = pd.DataFrame.from_dict(person_dicts)
df_boston_2019_1

26674 0
26699 25
26724 50

IndexError: list index out of range

In [45]:
boston_2019 = pd.read_csv('boston_marathon_results/boston_marathon_results_2019.csv')
#boston_2019 = boston_2019.drop('Unnamed: 0',axis=1)
boston_2019['country'] = boston_2019['Country']
boston_2019 = boston_2019.drop(['Unnamed: 0','Country'],axis=1)
boston_2019

,Year,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,bib_number,Age,Gender,City,State,Official Time,Net Time,country
0,2019,17778,10733,4132,"Aaflaq, Peter",Peter,Aaflaq,2245,19,M,Carbondale,IL,4:06:23,4:05:22,USA
1,2019,17139,10486,1355,"Aaldijk, Aart",Aart,Aaldijk,28431,51,M,Raamsdonksveer,NaN,4:29:06,4:01:42,NED
2,2019,12140,3752,2553,"Aames, Susie",Susie,Aames,14710,29,F,Alhambra,CA,3:45:33,3:41:06,USA
3,2019,296,275,237,"Aarnes, Hans Chr.",Hans Chr.,Aarnes,411,34,M,Nittedal,NaN,2:38:31,2:38:27,NOR
4,2019,5050,4445,804,"Aaronson, Matt",Matt,Aaronson,3781,43,M,Chicago,IL,3:15:23,3:13:29,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26756,2019,4971,592,499,"Zwickert, Kristy",Kristy,Zwickert,14554,36,F,Jerrabomberra,NaN,3:16:45,3:13:11,AUS
26757,2019,10777,7770,874,"Zwiller, Stéphane",Stéphane,Zwiller,10230,52,M,Fesches Le Chatel,NaN,3:37:26,3:35:55,FRA
26758,2019,9057,6926,75,"Zyborowicz, Henry",Henry,Zyborowicz,16505,62,M,Philadelphia,PA,3:29:38,3:29:19,USA
26759,2019,3,3,3,"Zybowski, Krys",Krys,Zybowski,H7,43,M,Avon,CT,1:13:36,1:13:36,USA
26760,2019,19510,11441,1141,"Zylka, Edward",Edward,Zylka,19326,59,M,S Burlington,VT,4:22:52,4:15:55,USA

In [38]:
boston_2021_mens = pd.read_csv('boston_marathon_results/boston_marathon_results_2021_mens.csv')
boston_2021_mens = boston_2021_mens.drop('Unnamed: 0',axis=1)
boston_2021_mens['Net Time']= boston_2021_mens['full_split']
boston_2021_mens['Official Time']= boston_2021_mens['finish_gun_time']
boston_2021_mens = boston_2021_mens.drop(['full_split','finish_gun_time'],axis=1)
boston_2021_mens['Year'] = 2021
boston_2021_mens['Gender'] = 'M'
boston_2021_mens

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,country,team,bib_number,half_marathon_split,Net Time,Official Time,Year,Gender
0,1,1,1,"Kipruto, Benson (KEN)",Benson,Kipruto,KEN,–,4,01:06:22,02:09:51,02:09:51,2021,M
1,2,2,2,"Berhanu, Lemi (ETH)",Lemi,Berhanu,ETH,–,3,01:06:23,02:10:37,02:10:37,2021,M
2,3,3,3,"Yimer, Jemal (ETH)",Jemal,Yimer,ETH,–,21,01:06:21,02:10:38,02:10:38,2021,M
3,4,4,4,"Ayana, Tsedat (ETH)",Tsedat,Ayana,ETH,–,12,01:06:22,02:10:47,02:10:47,2021,M
4,5,5,5,"Barsoton, Leonard (KEN)",Leonard,Barsoton,KEN,–,22,01:06:22,02:11:11,02:11:11,2021,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7937,15373,7938,729,"Wan, Yongbing (USA)",Yongbing,Wan,USA,–,11992,03:34:16,07:04:13,07:16:14,2021,M
7938,15374,7939,2232,"Roundtree, Ernest (USA)",Ernest,Roundtree,USA,–,3720,03:18:44,07:04:32,07:04:59,2021,M
7939,15380,7940,145,"Robinson, Harold (USA)",Harold,Robinson,USA,–,3546,03:35:08,07:22:59,07:31:36,2021,M
7940,15382,7941,2233,"Quinn, Adam (USA)",Adam,Quinn,USA,–,3698,02:53:29,07:24:34,07:24:56,2021,M
7941,15384,7942,1116,"Pierre, John (USA)",John,Pierre,USA,–,3714,03:38:05,07:51:35,07:51:47,2021,M

In [39]:
boston_2021_womens = pd.read_csv('boston_marathon_results/boston_marathon_results_2021_women.csv')
boston_2021_womens = boston_2021_womens.drop('Unnamed: 0',axis=1)
boston_2021_womens['Net Time']= boston_2021_womens['full_split']
boston_2021_womens['Official Time']= boston_2021_womens['finish_gun_time']
boston_2021_womens = boston_2021_womens.drop(['full_split','finish_gun_time'],axis=1)
boston_2021_womens['Year'] = 2021
boston_2021_womens['Gender'] = 'F'
boston_2021_womens

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,country,team,bib_number,half_marathon_split,Net Time,Official Time,Year,Gender
0,40,1,1,"Kiplagat, Edna (KEN)",Edna,Kiplagat,KEN,–,101,01:14:13,02:25:09,02:25:09,2021,F
1,41,2,1,"Ngugi, Mary (KEN)",Mary,Ngugi,KEN,–,119,01:14:12,02:25:20,02:25:20,2021,F
2,43,3,2,"Ngige, Monicah (KEN)",Monicah,Ngige,KEN,–,122,01:14:12,02:25:32,02:25:32,2021,F
3,45,4,3,"Gudeta, Netsanet (ETH)",Netsanet,Gudeta,ETH,–,126,01:14:12,02:26:09,02:26:09,2021,F
4,52,5,4,"Rojas, Nell (USA)",Nell,Rojas,USA,–,120,01:14:12,02:27:12,02:27:12,2021,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7437,15377,7438,880,"Stapleton, Tammy (USA)",Tammy,Stapleton,USA,–,17537,03:30:10,07:08:52,08:21:07,2021,F
7438,15378,7439,2840,"Lee, Sherry (USA)",Sherry,Lee,USA,–,4112,03:21:04,07:09:48,08:07:03,2021,F
7439,15379,7440,1288,"El Sherif Esposito, Rola (USA)",Rola,El Sherif Esposito,USA,–,19619,03:09:08,07:15:18,08:12:07,2021,F
7440,15381,7441,2841,"Sack, Jennifer (USA)",Jennifer,Sack,USA,–,18155,04:16:22,07:23:49,07:23:49,2021,F
7441,15383,7442,1289,"Cella, Tamara (USA)",Tamara,Cella,USA,–,16194,03:36:58,07:33:22,08:27:40,2021,F

In [34]:
boston_2022_womens = pd.read_csv('boston_marathon_results/boston_marathon_results_2022_women.csv')
boston_2022_womens = boston_2022_womens.drop('Unnamed: 0',axis=1)
boston_2022_womens['Net Time']= boston_2022_womens['full_split']
boston_2022_womens['Official Time']= boston_2022_womens['finish_gun_time']
boston_2022_womens = boston_2022_womens.drop(['full_split','finish_gun_time'],axis=1)
boston_2022_womens['Gender'] = 'F'
boston_2022_womens['Year'] = 2022
boston_2022_womens

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,country,team,bib_number,half_marathon_split,Net Time,Official Time,Gender,Year
0,31,1,1,"Jepchirchir, Peres (KEN)",Peres,Jepchirchir,KEN,–,102,01:09:41,02:21:01,02:21:01,F,2022
1,32,2,2,"Yeshaneh, Ababel (ETH)",Ababel,Yeshaneh,ETH,–,109,01:09:41,02:21:05,02:21:05,F,2022
2,33,3,3,"Ngugi, Mary (KEN)",Mary,Ngugi,KEN,–,117,01:10:20,02:21:32,02:21:32,F,2022
3,35,4,1,"Kiplagat, Edna (KEN)",Edna,Kiplagat,KEN,–,101,01:10:20,02:21:40,02:21:40,F,2022
4,37,5,4,"Ngige, Monicah (KEN)",Monicah,Ngige,KEN,–,118,01:10:20,02:22:13,02:22:13,F,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10562,24821,10568,1109,"Swanson, Kristin (USA)",Kristin,Swanson,USA,–,7785,03:09:59,06:38:53,06:39:02,F,2022
10563,24822,10569,1637,"Rogosheske, Valerie (USA)",Valerie,Rogosheske,USA,–,7783,03:10:00,06:38:54,06:39:03,F,2022
10564,24823,10570,4719,"Rogosheske, Abigail (USA)",Abigail,Rogosheske,USA,–,7784,03:10:01,06:38:56,06:39:03,F,2022
10565,24824,10571,10,"Rogosheske, Valerie (USA)",Valerie,Rogosheske,USA,–,1972,03:10:03,06:38:57,06:39:03,F,2022
10566,24828,10572,793,"Foulds, Rhonda (USA)",Rhonda,Foulds,USA,–,7620,03:01:15,06:49:43,06:50:13,F,2022

In [40]:
boston_2022_mens = pd.read_csv('boston_marathon_results/boston_marathon_results_2022_mens.csv')
boston_2022_mens = boston_2022_mens.drop('Unnamed: 0',axis=1)
boston_2022_mens['Net Time']= boston_2022_mens['full_split']
boston_2022_mens['Official Time']= boston_2022_mens['finish_gun_time']
boston_2022_mens = boston_2022_mens.drop(['full_split','finish_gun_time'],axis=1)
boston_2022_mens['Gender'] = 'M'
boston_2022_mens['Year'] = 2022
boston_2022_mens

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,country,team,bib_number,half_marathon_split,Net Time,Official Time,Gender,Year
0,1,1,1,"Chebet, Evans (KEN)",Evans,Chebet,KEN,–,4,01:03:26,02:06:51,02:06:51,M,2022
1,2,2,2,"Cherono, Lawrence (KEN)",Lawrence,Cherono,KEN,–,5,01:03:27,02:07:21,02:07:21,M,2022
2,3,3,3,"Kipruto, Benson (KEN)",Benson,Kipruto,KEN,–,1,01:03:26,02:07:27,02:07:27,M,2022
3,4,4,4,"Geay, Gabriel (TAN)",Gabriel,Geay,TAN,–,9,01:03:26,02:07:53,02:07:53,M,2022
4,5,5,5,"Kiptanui, Eric (KEN)",Eric,Kiptanui,KEN,–,11,01:03:26,02:08:47,02:08:47,M,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14256,24829,14257,1055,"Grossi, Anthony (USA)",Anthony,Grossi,USA,–,7658,03:00:39,06:55:49,07:02:00,M,2022
14257,24830,14258,1451,"Kent, Paul (USA)",Paul,Kent,USA,–,7681,02:54:15,06:56:35,06:57:17,M,2022
14258,24831,14259,1900,"Burros, Aaron (USA)",Aaron,Burros,USA,–,7638,03:04:52,06:58:12,07:04:14,M,2022
14259,24832,14260,1056,"Martin Arjona, Julian (ESP)",Julian,Martin Arjona,ESP,–,28701,02:58:05,06:58:50,07:04:26,M,2022
14260,24833,14261,4818,"Valenciano, Jorge (MEX)",Jorge,Valenciano,MEX,–,5398,03:19:31,07:01:32,07:04:53,M,2022

In [41]:
boston_2023_mens = pd.read_csv('boston_marathon_results/boston_marathon_results_2023_mens.csv')
boston_2023_mens = boston_2023_mens.drop('Unnamed: 0',axis=1)
boston_2023_mens['Net Time']= boston_2023_mens['full_split']
boston_2023_mens['Official Time']= boston_2023_mens['finish_gun_time']
boston_2023_mens = boston_2023_mens.drop(['full_split','finish_gun_time'],axis=1)
boston_2023_mens['Gender'] = 'M'
boston_2023_mens['Year'] = 2023
boston_2023_mens

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,Net Time,Official Time,Gender,Year
0,1,1,1,"Chebet, Evans",Evans,Chebet,–,1,01:02:20,02:05:54,02:05:54,M,2023
1,2,2,2,"Geay, Gabriel",Gabriel,Geay,–,3,01:02:20,02:06:04,02:06:04,M,2023
2,3,3,3,"Kipruto, Benson",Benson,Kipruto,–,5,01:02:19,02:06:06,02:06:06,M,2023
3,4,4,4,"Korir, Albert",Albert,Korir,–,19,01:02:20,02:08:01,02:08:01,M,2023
4,5,5,5,"Talbi, Zouhair",Zouhair,Talbi,–,31,01:02:20,02:08:35,02:08:35,M,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15171,26618,15173,1110,"Solberg, Bryon",Bryon,Solberg,–,7518,03:11:17,06:38:59,06:45:28,M,2023
15172,26619,15174,2050,"Davidson, Jonathan",Jonathan,Davidson,–,7520,02:39:22,06:40:56,06:47:13,M,2023
15173,26620,15175,2241,"Arai, Tatsuya",Tatsuya,Arai,–,3220,03:05:18,06:43:08,06:44:56,M,2023
15174,26622,15176,2051,"Weisberg, Scott",Scott,Weisberg,–,7593,03:27:15,07:04:20,07:10:42,M,2023
15175,26623,15177,2052,"Burros, Aaron",Aaron,Burros,–,7544,03:18:08,07:13:39,07:19:57,M,2023

In [42]:
boston_2023_womens = pd.read_csv('boston_marathon_results/boston_marathon_results_2023_women.csv')
boston_2023_womens = boston_2023_womens.drop('Unnamed: 0',axis=1)
boston_2023_womens['Net Time']= boston_2023_womens['full_split']
boston_2023_womens['Official Time']= boston_2023_womens['finish_gun_time']
boston_2023_womens = boston_2023_womens.drop(['full_split','finish_gun_time'],axis=1)
boston_2023_womens['Gender'] = 'F'
boston_2023_womens['Year'] = 2023
boston_2023_womens

,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,team,bib_number,half_marathon_split,Net Time,Official Time,Gender,Year
0,36,1,1,"Obiri, Hellen",Hellen,Obiri,–,122,01:11:29,02:21:38,02:21:38,F,2023
1,40,2,2,"Beriso, Amane",Amane,Beriso,–,102,01:11:30,02:21:50,02:21:50,F,2023
2,41,3,3,"Salpeter, Lonah",Lonah,Salpeter,–,105,01:11:29,02:21:57,02:21:57,F,2023
3,42,4,4,"Yeshaneh, Ababel",Ababel,Yeshaneh,–,116,01:11:30,02:22:00,02:22:00,F,2023
4,44,5,5,"Bates, Emma",Emma,Bates,–,121,01:11:30,02:22:10,02:22:10,F,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11418,26610,11419,527,"Magdaleno, Roselia",Roselia,Magdaleno,–,30985,02:52:35,06:25:34,06:29:38,F,2023
11419,26611,11420,4882,"Cooper, Rosalyn",Rosalyn,Cooper,–,14770,02:17:46,06:26:09,06:32:38,F,2023
11420,26613,11421,4883,"Myers, Laryssa",Laryssa,Myers,–,7781,02:42:01,06:30:07,06:35:37,F,2023
11421,26621,11422,815,"Foulds, Rhonda",Rhonda,Foulds,–,7552,03:09:48,06:56:34,07:02:44,F,2023
11422,26624,11423,4884,"Singh, Angela",Angela,Singh,–,25655,03:17:39,07:20:31,07:21:24,F,2023

In [46]:
frames = [boston_2019,boston_2021_mens,boston_2021_womens,boston_2022_mens, boston_2022_womens,boston_2023_mens, boston_2023_womens]

boston_combined = pd.concat(frames)
boston_combined

,Year,Place Overall,Place Gender,Place Division,full_name,first_name,last_name,bib_number,Age,Gender,City,State,Official Time,Net Time,country,team,half_marathon_split
0,2019,17778,10733,4132,"Aaflaq, Peter",Peter,Aaflaq,2245,19.0,M,Carbondale,IL,4:06:23,4:05:22,USA,NaN,NaN
1,2019,17139,10486,1355,"Aaldijk, Aart",Aart,Aaldijk,28431,51.0,M,Raamsdonksveer,NaN,4:29:06,4:01:42,NED,NaN,NaN
2,2019,12140,3752,2553,"Aames, Susie",Susie,Aames,14710,29.0,F,Alhambra,CA,3:45:33,3:41:06,USA,NaN,NaN
3,2019,296,275,237,"Aarnes, Hans Chr.",Hans Chr.,Aarnes,411,34.0,M,Nittedal,NaN,2:38:31,2:38:27,NOR,NaN,NaN
4,2019,5050,4445,804,"Aaronson, Matt",Matt,Aaronson,3781,43.0,M,Chicago,IL,3:15:23,3:13:29,USA,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11418,2023,26610,11419,527,"Magdaleno, Roselia",Roselia,Magdaleno,30985,NaN,F,NaN,NaN,06:29:38,06:25:34,NaN,–,02:52:35
11419,2023,26611,11420,4882,"Cooper, Rosalyn",Rosalyn,Cooper,14770,NaN,F,NaN,NaN,06:32:38,06:26:09,NaN,–,02:17:46
11420,2023,26613,11421,4883,"Myers, Laryssa",Laryssa,Myers,7781,NaN,F,NaN,NaN,06:35:37,06:30:07,NaN,–,02:42:01
11421,2023,26621,11422,815,"Foulds, Rhonda",Rhonda,Foulds,7552,NaN,F,NaN,NaN,07:02:44,06:56:34,NaN,–,03:09:48
11422,2023,26624,11423,4884,"Singh, Angela",Angela,Singh,25655,NaN,F,NaN,NaN,07:21:24,07:20:31,NaN,–,03:17:39

In [47]:
boston_combined.groupby(['Year','Gender']).count()

             Place Overall  Place Gender  Place Division  full_name  \
Year Gender
2019 F               11995         11995           11995      11995
     M               14766         14766           14766      14766
2021 F                7442          7442            7442       7442
     M                7942          7942            7942       7942
2022 F               10567         10567           10567      10567
     M               14261         14261           14261      14261
2023 F               11423         11423           11423      11423
     M               15176         15176           15176      15176

             first_name  last_name  bib_number    Age   City  State  \
Year Gender
2019 F            11995      11995       11995  11995  11994  10488
     M            14766      14766       14766  14766  14766  11205
2021 F             7442       7442        7442      0      0      0
     M             7942       7942        7942      0      0      0
2022 F            10567      10567       10567      0      0      0
     M            14261      14261       14261      0      0      0
2023 F            11423      11423       11423      0      0      0
     M            15176      15176       15176      0      0      0

             Official Time  Net Time  country   team  half_marathon_split
Year Gender
2019 F               11995     11995    11995      0                    0
     M               14766     14766    14766      0                    0
2021 F                7442      7442     7438   7442                 7442
     M                7942      7942     7940   7942                 7942
2022 F               10567     10567    10558  10567                10567
     M               14261     14261    14242  14261                14261
2023 F               11423     11423        0  11423                11423
     M               15176     15176        0  15176                15176

In [48]:
boston_combined.to_csv('boston_marathon_results_all.csv')

In [51]:
seattle_1 = pd.read_csv('seattle_marathon_top_1000.csv')
seattle_1

,PlaceSorting,BIB,Gender Place,Age Group Place,Age Group Gender Place,NAME,GENDER,AGE,7M Place,7M NET TIME,...,15.6M Place,15.6M NET TIME,16M Place,16M NET TIME,21M Place,21M NET TIME,23M Place,23M NET TIME,CHIP TIME,OVERALL PACE
0,1,1760,1 / 1199,1 / 206,1 / 140,Max Randal,Male,24,1.0,38:55:00,...,1.0,1:26:02,1.0,1:29:13,1.0,1:57:27,1.0,2:06:53,2:27:03,0:05:37
1,2,2807,2 / 1199,1 / 324,1 / 235,Nathan Richards,Male,31,3.0,39:49:00,...,2.0,1:28:14,2.0,1:31:33,2.0,2:00:17,2.0,2:09:23,2:29:58,0:05:44
2,3,1980,3 / 1199,1 / 202,1 / 143,Keith Laverty,Male,36,4.0,39:51:00,...,4.0,1:28:15,3.0,1:31:34,3.0,2:00:19,3.0,2:09:51,2:32:07,0:05:49
3,4,1211,4 / 1199,2 / 202,2 / 143,Joseph Darda,Male,36,7.0,39:53:00,...,6.0,1:28:19,4.0,1:31:34,4.0,2:00:53,5.0,2:10:34,2:32:11,0:05:49
4,5,2838,5 / 1199,2 / 324,2 / 235,Shaun Stephens-Whale,Male,34,2.0,39:49:00,...,5.0,1:28:18,5.0,1:31:35,5.0,2:00:53,4.0,2:10:33,2:32:46,0:05:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2472,758 / 1199,93 / 160,79 / 125,Andrew Hesky,Male,40,595.0,1:02:10,...,742.0,2:21:24,749.0,2:27:00,858.0,3:23:06,946.0,3:45:27,4:30:13,0:10:19
996,997,2753,238 / 520,275 / 431,79 / 155,Rylie McGinnis,Female,26,1090.0,1:10:12,...,1075.0,2:34:39,1076.0,2:40:25,1027.0,3:32:20,1020.0,3:49:55,4:30:18,0:10:19
997,998,1675,759 / 1199,192 / 324,152 / 235,Michael Duprey,Male,34,1118.0,1:10:47,...,1064.0,2:34:18,1074.0,2:40:17,1037.0,3:33:11,1024.0,3:50:30,4:30:19,0:10:19
998,999,2539,760 / 1199,94 / 160,80 / 125,Ronan Teyssier,Male,43,1405.0,1:17:10,...,1305.0,2:47:28,1296.0,2:53:21,1152.0,3:42:35,1114.0,3:58:06,4:30:19,0:10:19
999,1000,1316,761 / 1199,276 / 431,197 / 276,Harshit Agarwal,Male,29,1170.0,1:11:35,...,1071.0,2:34:31,1060.0,2:39:49,978.0,3:29:21,984.0,3:47:47,4:30:26,0:10:19

In [50]:
seattle_2 = pd.read_csv('seattle_2023_2.csv')
seattle_2

,PlaceSorting,BIB,Gender Place,Age Group Place,Age Group Gender Place,NAME,GENDER,AGE,7M Place,7M NET TIME,...,15.6M Place,15.6M NET TIME,16M Place,16M NET TIME,21M Place,21M NET TIME,23M Place,23M NET TIME,CHIP TIME,OVERALL PACE
0,1001,3205,762 / 1199,121 / 202,96 / 143,Kittipong Daijaroensuk,Male,38,573.0,1:01:34,...,800.0,2:23:49,804,2:29:23,884.0,3:25:12,961.0,3:46:19,4:30:26,0:10:19
1,1002,1614,239 / 520,277 / 431,80 / 155,Brianna Vance,Female,29,813.0,1:05:08,...,866.0,2:26:14,860,2:31:43,982.0,3:29:38,972.0,3:46:49,4:30:27,0:10:19
2,1003,1169,763 / 1199,122 / 202,97 / 143,Daniel Harden,Male,35,983.0,1:08:28,...,1138.0,2:37:35,1124,2:42:49,1011.0,3:31:45,1044.0,3:51:37,4:30:31,0:10:20
3,1004,1009,240 / 520,45 / 92,28-Dec,Merry Mullins,Female,51,759.0,1:04:27,...,1011.0,2:32:37,1005,2:38:17,1094.0,3:38:17,1089.0,3:55:59,4:30:43,0:10:20
4,1005,3319,241 / 520,278 / 431,81 / 155,Serena Allendorfer,Female,25,1103.0,1:10:32,...,1033.0,2:33:46,1034,2:39:30,1004.0,3:31:05,1026.0,3:50:39,4:30:44,0:10:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,1719,1623,1198 / 1199,65 / 65,42 / 42,Sean Matlock,Male,56,1696.0,1:50:47,...,1716.0,4:17:50,1718,4:28:29,1697.0,6:01:22,1716.0,6:30:57,7:40:20,0:17:34
719,1720,2312,518 / 520,324 / 324,86 / 86,Ghadah Gadi,Female,34,1658.0,1:32:57,...,1694.0,3:44:54,1698,3:57:47,1690.0,5:41:12,1710.0,6:17:13,7:51:10,0:17:59
720,1721,1788,519 / 520,29 / 29,9-Sep,Linda Denise Salo,Female,61,1697.0,1:51:29,...,1718.0,4:39:36,1720,4:51:06,1698.0,6:29:35,1717.0,7:04:28,8:09:15,0:18:40
721,1722,1419,1199 / 1199,160 / 160,125 / 125,Josh Graves,Male,43,1700.0,1:56:31,...,1719.0,4:44:28,1721,4:54:39,NaN,NaN,NaN,NaN,8:10:27,0:18:43
722,1723,1654,520 / 520,1-Jan,1-Jan,Jahna Prine,Female,79,1703.0,2:08:04,...,1720.0,4:49:48,1722,5:01:43,1699.0,6:39:51,1718.0,7:09:33,8:21:15,0:19:08

In [53]:
frames = [seattle_1,seattle_2]

seattle_combined = pd.concat(frames)
seattle_combined['Year'] = 2023
seattle_combined

,PlaceSorting,BIB,Gender Place,Age Group Place,Age Group Gender Place,NAME,GENDER,AGE,7M Place,7M NET TIME,...,15.6M NET TIME,16M Place,16M NET TIME,21M Place,21M NET TIME,23M Place,23M NET TIME,CHIP TIME,OVERALL PACE,Year
0,1,1760,1 / 1199,1 / 206,1 / 140,Max Randal,Male,24,1.0,38:55:00,...,1:26:02,1.0,1:29:13,1.0,1:57:27,1.0,2:06:53,2:27:03,0:05:37,2023
1,2,2807,2 / 1199,1 / 324,1 / 235,Nathan Richards,Male,31,3.0,39:49:00,...,1:28:14,2.0,1:31:33,2.0,2:00:17,2.0,2:09:23,2:29:58,0:05:44,2023
2,3,1980,3 / 1199,1 / 202,1 / 143,Keith Laverty,Male,36,4.0,39:51:00,...,1:28:15,3.0,1:31:34,3.0,2:00:19,3.0,2:09:51,2:32:07,0:05:49,2023
3,4,1211,4 / 1199,2 / 202,2 / 143,Joseph Darda,Male,36,7.0,39:53:00,...,1:28:19,4.0,1:31:34,4.0,2:00:53,5.0,2:10:34,2:32:11,0:05:49,2023
4,5,2838,5 / 1199,2 / 324,2 / 235,Shaun Stephens-Whale,Male,34,2.0,39:49:00,...,1:28:18,5.0,1:31:35,5.0,2:00:53,4.0,2:10:33,2:32:46,0:05:50,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,1719,1623,1198 / 1199,65 / 65,42 / 42,Sean Matlock,Male,56,1696.0,1:50:47,...,4:17:50,1718.0,4:28:29,1697.0,6:01:22,1716.0,6:30:57,7:40:20,0:17:34,2023
719,1720,2312,518 / 520,324 / 324,86 / 86,Ghadah Gadi,Female,34,1658.0,1:32:57,...,3:44:54,1698.0,3:57:47,1690.0,5:41:12,1710.0,6:17:13,7:51:10,0:17:59,2023
720,1721,1788,519 / 520,29 / 29,9-Sep,Linda Denise Salo,Female,61,1697.0,1:51:29,...,4:39:36,1720.0,4:51:06,1698.0,6:29:35,1717.0,7:04:28,8:09:15,0:18:40,2023
721,1722,1419,1199 / 1199,160 / 160,125 / 125,Josh Graves,Male,43,1700.0,1:56:31,...,4:44:28,1721.0,4:54:39,NaN,NaN,NaN,NaN,8:10:27,0:18:43,2023
722,1723,1654,520 / 520,1-Jan,1-Jan,Jahna Prine,Female,79,1703.0,2:08:04,...,4:49:48,1722.0,5:01:43,1699.0,6:39:51,1718.0,7:09:33,8:21:15,0:19:08,2023

In [54]:
seattle_combined.to_csv('seattle_marathon_results_all.csv')